### ISSUE TITLE
Unexpected behavior of the 'optional' method

### ISSUE THREAD

**Issue by artbq** [dry-rb/dry-types#102]
Good day!

This is what I currently get in the terminal:

```
2.3.0 :001 > require "dry-types"
 => true 
2.3.0 :002 > include Dry::Types.module
 => Object 
2.3.0 :003 > Strict::String.optional[nil]
 => nil 
2.3.0 :004 > Maybe::Strict::String[nil]
 => None 
```

But after reading doc at http://dry-rb.org/gems/dry-types/optional-values/, I've expected that the output of the last two commands would be the same.

**Comment by flash-gordon** [comment]
We have changed the meaning of `.optional` method some time ago so it now returns a plain sum type instead of a maybe type. The docs you're viewing are for a released version of the gem. If you use the gem from master branch you now need to call `.maybe` in order to get a maybe type.
Like this:
```ruby
Strict::String.maybe[nil] 
=> None
```

**Comment by artbq** [comment]
Got it. Thank you for the explanation.
