### ISSUE TITLE
Struct#to_h returns Some and None

### ISSUE THREAD

**Issue by soylent** [dry-rb/dry-types#103]
Hello, I found the following issue with method `to_h`:

```ruby
class Foo < Dry::Types::Struct
  attribute :bar, 'maybe.strict.string'
end

attrs = { bar: 'qux' }
foo = Foo.new(attrs)

foo.to_h == attrs #=> false
foo.to_h #=> {:bar=>Some("qux")}
```

Expected:

```ruby
foo.to_h #=> {:bar=>"qux"}
```

Could you please confirm if this is a bug?

**Comment by flash-gordon** [comment]
Hello, @soylent, why do you expect `#to_h` to return an unwrapped value? All what this method actually does is calling methods on your struct and forming a hash based on the list of attributes. Maybe type is not a special case here, you can "invent" your own type that wraps values, there is no common interface on unwrapping them. If you want to serialize your struct to something plain like JSON I guess you should define it _outside_ of the struct. It's more verbose but more flexible either.
