### ISSUE TITLE
different results between Types::Form::Decimal and Types::Coercible::Decimal

### ISSUE THREAD

**Issue by artworx** [dry-rb/dry-types#104]
Example: 

``` ruby
> Types::Coercible::Decimal["10."]
 => #<BigDecimal:5fb93e8,'0.1E2',9(18)> 

> Types::Form::Decimal["10."]                                                                                                                                                                         
"\"10.\""
```

This seems to be caused by [coercions#to_decimal](https://github.com/dry-rb/dry-types/blob/master/lib/dry/types/coercions/form.rb#L43) using `to_float`

**Comment by solnic** [comment]
hey @fran-worley this seems to be related to recent changes, but I honestly don't know if we should accept this notation for decimals. I wonder what AM::V does.

**Comment by fran-worley** [comment]
@solnic just to check with AM::V do you mean what they accept as true for their `numericality` validator? I personality don't like that notation at all, but we should be consistent and return the same for both.

**Comment by solnic** [comment]
More specifically - I wonder how coercion in AR works for such cases. Then we also have `.10` heh :)

**Comment by fran-worley** [comment]
I don't know if this helps but in 4.2 AR casts to decimals as follows:
https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/type/decimal.rb#L16-L28

**Comment by fran-worley** [comment]
Though it is worth noting that "10." would fail AM::V validations as it uses FLOAT which won't pass it.

https://github.com/rails/rails/blob/89e2f7e722e06f900bdb1c14db33073c90d7cdea/activemodel/lib/active_model/validations/numericality.rb#L76

**Comment by flash-gordon** [comment]
I checked `master`, `Types::Coercible::Decimal["10."]` now raises an error meaning the behavior is consistent with `Params::Decimal`. I'll close this but feel free to comment if you have any objections
