### ISSUE TITLE
Setters for attributes in Dry::Types::Struct

### ISSUE THREAD

**Issue by bbozo** [dry-rb/dry-types#106]
Hey all :)

I'm just wondering, why doesn't struct generate setters for the attributes? I.e. I want to push around a serializeable transaction context and I define the non-volatiles as attributes:

``` ruby
class Context < Dry::Types::Struct
  constructor_type(:schema) # this seems to be necessary unless you want to list all of the attributes in the initializer

  HashContainer = Types::Strict::Hash.default({})
  NilOrInt = Types::Strict::Nil | Types::Coercible::Int # seems that Types::Maybe::Strict::Int.default(nil) isn't allowed but they provide a workaround in the docs

  # Client request-response context
  attribute :request,  HashContainer
  attribute :response, HashContainer

  # Persisted trx data context
  attribute :t_request,  HashContainer
  attribute :t_response, HashContainer

  # Acquirer request-response context
  attribute :acq_request,  HashContainer
  attribute :acq_response, HashContainer

  attribute :merchant_id, NilOrInt
end

ctx = Context.new
ctx.request[:merchant_id] = 3 # OK
ctx.merchant_id = 3 # NoMethodError
```

Note on the use case, I don't use `Dry::Types` here to validate user input, I already do it in a separate class, this is to hold the environment of a transaction for passing it down the processing pipeline (a railway-inspired flow I'm playing with after seeing `dry-transaction`).

**Comment by timriley** [comment]
We want to encourage struct objects to be treated as immutable, which is why we don't provide setters. In this case, you'd probably just need to go ahead and add the writers to your own `Context` class.

**Comment by bbozo** [comment]
@timriley, consider the following scenario, it's kind of typical in request-response processing with a bunch of "middle steps" (be it composed functions like in `dry-transaction` or middlewares in `rack` and `faraday`) that the context of the request-response cycle grows as the mid-steps progress,

in the Rack example it would be content headers, oauth attributes etc, and in my use case it's raw request attributes, standardized request attributes, acquirer request attributes, acquirer response attributes etc,

do you have a suggestion on how to handle this "growing env" pattern with DStruct? Apart from "hashes everywhere"? :) Is there a way with which you can create a new DStruct with, for example, just merchant_id of different value and the rest of the DStruct the same?

**Comment by bbozo** [comment]
Wowww, just  a heads-up, trying to slap `attr_writer` to attributes results in some funny shit:

``` ruby
    attribute :acq_request,  HashContainer; attr_writer :acq_request

    # https://github.com/dry-rb/dry-types/issues/106
    attribute :env, HashContainer

    def validation_error! message
      puts "!!!! #{acq_request}"
      env[:validation_error] ||= message
      puts "???? #{acq_request}"
    end
```

when stars co-align (and they co-align 60% of the time) results with:

```
!!!! {}
???? {:validation_error=>"Digest is wrong"}
```

**Comment by timriley** [comment]
Thanks for the extra context, @bbozo. As it stands right now, I don't think Dry::Types::Struct is really appropriate for the kind of behaviour you describe. It's really just designed right now to hold values, not anything that has to have its state mutated over time. It feels to me like it might be a better outcome for you if you made a properly suited custom class to offer exactly the behaviour you want, using dry-types as necessary for any sort of type checking you'd like along the way.

**Comment by jdickey** [comment]
@bbozo @timeriley agreed; I just got bitten by this in the new 0.8.0 release with `Dry::Types::Value`. I'd previously understood that class to carry semantics of

> Create a value object where, once instantiated, the attribute values cannot be changed; e.g., by assigning a new value to an attribute.

As of 0.8.0, it seems to be more along the lines of

> Create a "[deep frozen](https://github.com/dkubb/ice_nine)" value object where, once instantiated, the attribute values cannot be changed, and each attribute value references an immutable object instance.

My understanding now is that, for the first semantics, what I want is a `Dry::Types::Struct`; the attributes may or may not be `#frozen?` themselves, but the objects they reference are guaranteed not to have been deep-frozen by virtue of being an attribute in the `Dry::Types::Struct`.

**Comment by bbugh** [comment]
@bbozo did you settle on a solution? `dry-struct` is a perfect solution for our use case... except the lack of writers. It'll be annoying to have to define writers for every struct and every attribute - too much room for error. We can write our own `attribute` method that builds writers, but we're trying to write less custom code, not more.

I'm curious if you found something else that is strongly typed like this that allows built-in writers.

**Comment by pablocrivella** [comment]
After taking a look into the internals of `Dry::Struct` i ended up implementing this class:

```ruby
class StructWithSetters < Dry::Struct
  # Convert string keys to symbols
  transform_keys(&:to_sym)

  # Resolve default types on nil
  transform_types do |type|
    if type.default?
      type.constructor do |value|
        value.nil? ? Dry::Types::Undefined : value
      end
    else
      # Make all types omittable
      type.meta(omittable: true)
    end
  end

  def self.attribute(name, type = nil, &block)
    super
    define_attribute_setter(name)
  end

  def self.define_attribute_setter(name)
    define_method("#{name}=") do |value|
      self.attributes = attributes.merge(name => value)
    end
  end

  def attributes=(new_attributes)
    @attributes = self.class.input[new_attributes]
  end
end
```

I tried to implement something that would work with the `transform_keys` and `transform_types` methods.
@flash-gordon @timriley do you have some comments on the approach i took? Thanks in advance :)
