### ISSUE TITLE
#to_hash should use consistent key types

### ISSUE THREAD

**Issue by dNitza** [dry-rb/dry-types#110]
Given an entity:

`#<MyEntity id=1 content={"lender"=>{"contact_person"=>{"name"=>""} } "borrowers"=>[{"member_name"=>{"first_name"=>""}}] }>`

Calling `to_hash` will return a hash with a mixture of key types:

`{:id=>1, :content={"lender"=>{"contact_person"=>{"name"=>""} } "borrowers"=>[{"member_name"=>{"first_name"=>""}}] }}`

which causes access issues later on.

```ruby
def to_hash
  self.class.schema.keys.each_with_object({}) do |key, result|
    result[key] = Hashify[self[key]]
  end
end
```
Having a look through the `to_hash` method implementation, it looks as though the key could be either a symbol or a string depending on what is defined in the entity. Is that right?

I'm wondering if `to_hash` should recursively symbolise keys (including in arrays) so we can work with a consistent type of key?

**Comment by solnic** [comment]
Could you show me how `MyEntity` definition looks like?

**Comment by dNitza** [comment]
Sure, it looks like this:

```ruby
class MyEntity < Dry::Types::Struct
  attribute :id, Types::Strict::Int
  attribute :client_id, Types::Strict::Int
  attribute :file_handler_id, Types::Strict::Int
  attribute :matter_number, Types::Strict::String
  attribute :type, Types::Strict::String
  attribute :status, Types::Strict::String
  attribute :created_at, Types::Strict::Time
  attribute :content, Types::Coercible::Hash
end
```

**Comment by solnic** [comment]
Since you define `:content` as a simple coercible hash you can't expect it to be coerced into a symbolized hash. This is actually the expected behavior. If you want it to coerce string keys to symbols you need to define it like that:

``` ruby
attribute :content, Types::Coercible::Hash.symbolized(
  # define all the keys here, including nested symbolized hashes
)
```

**Comment by dNitza** [comment]
Oh nice :) No problems then. I will change my approach and close this issue.

Thanks!
