### ISSUE TITLE
valid? method is inconsistent with #[]

### ISSUE THREAD

**Issue by hieuk09** [dry-rb/dry-types#112]
When using `Array` with `member`, `valid?` and `#[]` behaves differently:

```ruby
module Types
  include Dry::Types.module
  SegmentIDs = Strict::Array.member(Strict::String)
end

Types::SegmentIDs.valid?([1, 2]) # => true
Types::SegmentIDs[[1, 2]] # => raise Dry::Types::ConstraintError
```

IMHO, `valid?` should return false if the members in the array violate the constraint in this case.

**Comment by solnic** [comment]
Thanks for the report. Definitely a bug.

**Comment by roryokane** [comment]
Here’s a unit test that reproduces this. Put it [in `spec/dry/types/array_spec.rb`](https://github.com/dry-rb/dry-types/blob/e0159b53b373a5dca3be2239ccdb7f4ebc6ee3a2/spec/dry/types/array_spec.rb#L37-L38) within the scope `context 'primitive'`.

```ruby
context 'testing validity with #valid?' do
  subject(:array) { Dry::Types['strict.array'].member(Dry::Types['strict.string']) }

  it 'detects invalid input of the completely wrong type' do
    expect( array.valid?( 5 ) ).to be false
  end

  it 'detects invalid input of the wrong member type' do
    expect( array.valid?( [5] ) ).to be false
  end

  it 'recognizes valid input' do
    expect( array.valid?( ['five'] ) ).to be true
  end
end
```

The first and last tests pass, but the middle one, “detects invalid input of the wrong member type”, fails.

I’m guessing the fix to this problem will go in `lib/dry/types/array/member.rb`. However, I don’t know enough about dry-types to fix this bug myself. That’s why I’m not making a pull request with these tests – I’m assuming you don’t want still-failing tests in `master`.

**Comment by solnic** [comment]
@roryokane thanks, that's very helpful. I'm busy with other gems these days but I'll get to it sooner or later :)

**Comment by hieuk09** [comment]
@solnic 👍
