### ISSUE TITLE
Do we need a register DSL for Dry::Types.module ?

### ISSUE THREAD

**Issue by nepalez** [dry-rb/dry-types#115]
What do you think about polluting Dry::Types.module with a method like this

``` ruby
def self.register(type, as: type)
  key = Dry::Types.identifier(as)

  unless Dry::Types.type_keys.include? key
    type = Dry::Types::Definition[type].new(type) if Class === type
    Dry::Types.register key, definition
    Dry::Types.define_constants self, [key]
  end

  Dry::Types[key]
end
```

IMO this could provide a bit prettier DSL for including types:

``` ruby
module MyTypes
  include Dry::Types.module

  register ::Regexp # registers new primitive from the class
  register Regexp.constrained(type: ::Regexp), as: 'strict.regexp'
  # etc
end
```

**Comment by flash-gordon** [comment]
I'm not sure how this can help and why plain constants worse than having a container. I must be missing a use case for this but since it's a discussion issue feel free to raise it again [on the forum](https://discourse.dry-rb.org/) and elaborate, I'll be happy to discuss.
