### ISSUE TITLE
Question: Does Maybe type causes coupling?

### ISSUE THREAD

**Issue by Kukunin** [dry-rb/dry-types#116]
Hello. First of all, thanks a lot for such great suit of gems for Ruby. This is exactly what I was looking long time since I started to care about architecture. 

Currently, I try to utilize `dry-types` in my project, and noticed one thing with optional (Maybe) types

```ruby
class MyClass < Dry::Types::Struct
  include Dry::Types.module

  attribute :optional, Maybe::Strict::String
end

obj = MyClass.new
=> #<MyClass optional=None>
obj.optional
=> None
obj.optional.value
=> nil
```

That fact, that getter returns Monad but real value, just because attribute is optional, changes default client's use of that getter: client needs to send `value` method to get real value.

Validation is matter to be changed, and thus should be encapsulated inside object and decoupled from rest of code. But currently, changing attribute optionality from `Maybe::Strict::String` to `Strict::String` requires update of every client code, because there is no `value` method anymore.
That creates coupling between client's use of attribute and attribute optionality.

I hope you understand my question fully. Thanks!

**Comment by solnic** [comment]
That's intentional so that handing of `nil` is explicit and required. Coupling is not a problem because it's like being worried that if you change an attr from String to Fixnum then you need to change code that depends on it :)
