### ISSUE TITLE
.optional type enforcing .constrained even when nil

### ISSUE THREAD

**Issue by d-Pixie** [dry-rb/dry-types#122]
If I define a type like this:

``` ruby
CountryCode = Types::Strict::String.optional.constrained( included_in: CountryCodes.values ).constructor{|v| v.to_s.upcase[0...2] unless v.nil? }
```

I would expect it to be able to have either `nil`or any member of `CountryCodes.values` as value.

It seems that the constraint is always in effect though and triggers when I try to initialise it to nil. What is expected behaviour here? If the above **is** the expected behaviour; is there any way of getting what I want?

**Comment by d-Pixie** [comment]
Given that this is in the test suit:
```ruby
context 'with an optional sum type' do
    subject(:type) do
      Dry::Types['string'].constrained(size: 4).optional
    end

    it 'passes when constraints are not violated' do
      expect(type[nil]).to be(nil)
      expect(type['hell']).to eql('hell')
    end

    ...

  end
```
it looks like the behaviour from above is a bug.

**Comment by d-Pixie** [comment]
Ok, I found it ... It's operator precedence :) If I change it to:
```ruby
CountryCode = Types::Strict::String.constrained( included_in: CountryCodes.values ).optional.constructor{|v| v.to_s.upcase[0...2] unless v.nil? }
```
It works, notice the moved `.optional`.

Shouldn't the "optionality" set during type construction be preserved no matter where in the method chain it comes?

**Comment by solnic** [comment]
I'll try to improve it one way or the other. It'd be perfect if the order didn't matter but it may turn out to be tricky, we'll see what makes sense.
