### ISSUE TITLE
Add Types::Object type

### ISSUE THREAD

**Issue by Kukunin** [dry-rb/dry-types#123]
This allows to accept any object, and constraint to objects of some specific class. Like:

``` ruby
MyClassType = Types::Object.constrained(type: MyClass)
```

**Comment by padde** [comment]
@solnic is this something you would consider? I would have found this quite helpful as well. For example, I have used the following workaround to create a `Money` type, but it seems a bit 'dirty' in that it is using non-documented methods:

```
module Types
  include Dry::Types.module

  module Coercions
    module Form
      def self.to_money(value)
        ::Money.parse(value)
      rescue ArgumentError, TypeError
        value
      end
    end
  end

  Money = Dry::Types::Definition[::Money].new(::Money)
  Coercible::Money = Money.constructor(::Money.method(:parse))
  Form::Money = Money.constructor(Coercions::Form.method(:to_money))
end
```

**Comment by solnic** [comment]
Yes this will be useful
