### ISSUE TITLE
Initialize with Hash, which doesn't suit type

### ISSUE THREAD

**Issue by openscript** [dry-rb/dry-types#127]
Let's say the following type is given:
```
class User < Dry::Types::Struct
  attribute :name, Types::Maybe::Coercible::String
  attribute :age, Types::Maybe::Coercible::Int
end
```
So the `name` and `age` are optional. Shouldn't it be possible to initialize an object of that type with:
```
User.new({})
```
or
```
User.new({name: 'Robert')
```
This will throw an error.

**Comment by flash-gordon** [comment]
@openscript this is a quite-well-known issue :) You need to change `constructor_type` like this:
```ruby
class User < Dry::Types::Struct
  constructor_type :schema
  
  attribute :name, Types::Maybe::Coercible::String
  attribute :age, Types::Maybe::Coercible::Int
end
```
We'll address this in the docs once we release dry-struct, it is an extraction of `Dry::Types::Struct` from dry-t /cc @backus

**Comment by openscript** [comment]
@flash-gordon Thank you very much for the quick, helpful answer! :-)

**Comment by backus** [comment]
Yeah this is a planned fix for `Dry::Struct`
