### ISSUE TITLE
Optional in Hash Input for Struct

### ISSUE THREAD

**Issue by AlexRiedler** [dry-rb/dry-types#128]
I have a few cases when doing `StructClass.new(foo: 1, bar: 2)` and there is an attribute e.g. `baz` that has a default value where it feels pretty unnecessary to have to specify baz in the call.

Not sure if I am missing how to do this, or it doesn't support it.

Thanks for any help :)

**Comment by flash-gordon** [comment]
@AlexRiedler is this what you're looking for https://github.com/dry-rb/dry-types/issues/127#issuecomment-241357190 ?

**Comment by AlexRiedler** [comment]
Yup @flash-gordon thanks for the quick reply; that will work :)
