### ISSUE TITLE
Surprising results for Form::Date.optional

### ISSUE THREAD

**Issue by padde** [dry-rb/dry-types#129]
Types::Form::Date works like this:

```
Types::Form::Date[nil]
# TypeError: no implicit conversion of nil into String
# from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/dry-types-0.8.1/lib/dry/types/coercions.rb:11:in `parse'

Types::Form::Date['']
#=> ""

Types::Form::Date['2016-01-01']
#=> Fri, 01 Jan 2016
```

but when we make the type optional in order to accept `nil` as value, it does no longer accept "invalid" date strings:

```
Types::Form::Date.optional[nil]
#=> nil

Types::Form::Date.optional['']
# Dry::Types::ConstraintError: "" violates constraints (#<struct Dry::Types::Result::Failure input="", error="\"\" must be an instance of Date">)
# from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/dry-types-0.8.1/lib/dry/types/sum.rb:40:in `block in call'

Types::Form::Date.optional['2016-01-01']
#=> Fri, 01 Jan 2016
```

Is this intentional or a bug? What would be the appropriate way to implement an optional Form::Date?

**Comment by solnic** [comment]
Oh that's interesting, it is intentional since `optional` helper simply does `Types::Strict::Nil | Types::Form::Date` but we could make it smarter. For now this will work for you:

``` ruby
irb(main):008:0> (Types::Form::Nil | Types::Form::Date)['']
=> nil
irb(main):009:0> (Types::Form::Nil | Types::Form::Date)['2016-05-04']
=> #<Date: 2016-05-04 ((2457513j,0s,0n),+0s,2299161j)>
```

The reason why it works like that is that `Types::Form::Nil` knows that an empty string should be coerced to `nil`.

Anyhow, I'm gonna leave this open as we could improve `Type#optional` behavior.

**Comment by solnic** [comment]
Actually I reported a new issue about this #130

**Comment by padde** [comment]
@solnic thanks, but my use case is actually not with empty strings, but rather with invalid user input:

```
[89] pry(main)> (Types::Form::Nil | Types::Form::Date)['foo']
Dry::Types::ConstraintError: "foo" violates constraints (#<struct Dry::Types::Result::Failure input="foo", error="\"foo\" must be an instance of Date">)
from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/dry-types-0.8.1/lib/dry/types/sum.rb:40:in `block in call'
```

whereas

```
[90] pry(main)> Types::Form::Date['foo']
=> "foo"

**Comment by padde** [comment]
In #130 you note that this happens with types that perform nil coercion (I assume from an empty string to nil?) but this is not actually the case here. It will rather return an empty string back:

```
Types::Form::Date['']
#=> ""
```

**Comment by padde** [comment]
I assume a possible workaround would be:

```
(Types::Coercible::String | Types::Form::Date).optional

# or

(Types::Form::Nil | Types::Coercible::String | Types::Form::Date).optional
```

**Comment by solnic** [comment]
@padde ok so there's another issue here where sum type doesn't behave well for invalid input in a form type. I'll look into this. Seems like a bug.

re coercion, `Types::Form::Nil` does it, so you need to sum `Form::Nil` with another one to get a `nil` back from an empty string.

**Comment by padde** [comment]
re coercion, I don't necessarily need/want `nil` back for an empty string although it would simplify things compared to our current implementation. The actual use case is that we want to display a validation error rather than raising a coercion error with invalid inputs. Still, it should be possible to omit the input (either by not including the field at all or by having the user submit an empty string).

**Comment by solnic** [comment]
@padde for validation pls use dry-validation...dry-types are not meant to be used for data validation

**Comment by padde** [comment]
@solnic currently in the process of migrating from reform 1.x with extensive use of activemodel validations 😉 The validation basically just checks if the supplied value `is_a?(Date)` which seems to work fine otherwise.

I can live with the workarounds above for now though, again thanks a lot for your help.

**Comment by padde** [comment]
@solnic it feels somehow inconsistent that `Types::Form::{Date,Time,DateTime}` will not accept `nil`, whereas all other form types do accept it. I realize this is due to the way the core `Date.parse` etc. methods work.

What's you opinion on that? Is this something that should be changed or is it intentional?

**Comment by solnic** [comment]
So other types return nil back? We should make this consistent for sure. I wanted Form types to work exclusively with string, hash and array types as potential input and nil should crash in all cases tbh as this is not an expected input with form data parsed by rack. OTOH I was told there are cases where some middleware may add something to params that can have different types (ie an integer, or nil) so we may want to tweak Form types to accept nil or already coerced values

**Comment by padde** [comment]
@solnic yeah they do:

```
Types::Form::Int[nil]
=> nil
```

this was most probably introduced with https://github.com/dry-rb/dry-types/commit/273e9e8c7631e822bd9a30324e2b120b11dbe9ec if you observe:

```
[12] pry(main)> Integer(nil)
TypeError: can't convert nil into Integer
from (pry):16:in `Integer'
```

I also think either all or no form types should accept nil. If all accept nil this would also solve my original problem because then I wouldn't have to make it optional in the first place :)

**Comment by padde** [comment]
re already coerced values, I think it makes much sense to accept already coerced values with any type. Although it might not be a frequent use case, I cannot think of a case where this would be hurtful.

**Comment by solnic** [comment]
I'd accept a patch which makes time/date related `Form` types fail gracefully and return original input. Is this something you could do?

**Comment by padde** [comment]
Cool. Sure, I'll give it a shot!

**Comment by ZombieHarvester** [comment]
@solnic 
> nil should crash in all cases tbh as this is not an expected input with form data parsed by rack

input doesn't alway come from web forms, it can be API or CSV import, where date can be nil or invalid format. In my case its CSV and i'm facing the same issue

**Comment by solnic** [comment]
@ZombieHarvester of course, but `Form::*` types shouldn't be used in such cases, we're optimizing them for a very specific use-case which is rack request params.

There's nothing stopping us from adding a more generic (thus much more complex and slower) coercible types, that would support many types of input. I'm more than happy to accept a PR which adds that :)

**Comment by flash-gordon** [comment]
I checked all described issues on master and everything seems to work fine now so I'm closing this issue, feel free to comment tho.
