### ISSUE TITLE
Make Type#optional smarter

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-types#130]
Right now this method assumes `Types::Strict::Nil` but when it's used in conjunction with types that have nil coercion, like `Types::Form`, then it's gonna behave in an unexpected way from the usage pov. See #129 as an example.

**Comment by GustavoCaso** [comment]
@solnic is this issue still open for help ?

**Comment by solnic** [comment]
@GustavoCaso oh thanks, but actually https://github.com/dry-rb/dry-types/pull/178 is much more important, and it's a simpler one. How do you feel about helping with that instead?

**Comment by GustavoCaso** [comment]
@solnic great I will work on that one

**Comment by flash-gordon** [comment]
As far as I can tell, it's smart enough now
```ruby
[14] pry(main)> Types::Params::Date.optional['123123']
=> "123123"
[15] pry(main)> Types::Params::Date.optional['123']
=> #<Date: 2018-05-03 ((2458242j,0s,0n),+0s,2299161j)>
[16] pry(main)> Types::Params::Date.optional[nil]
=> nil
```
