### ISSUE TITLE
Some form types do not accept their target type for coercion

### ISSUE THREAD

**Issue by padde** [dry-rb/dry-types#131]
Most form types accept an object of the target type for coercion:

```
[23] pry(main)> Types::Form::Int[1]
=> 1
[24] pry(main)> Types::Form::Float[1.0]
=> 1.0
```

I would assume that this also works with dates, but currently it throws an error instead of returning the date object.

```
[8] pry(main)> Types::Form::Date[Date.new]
TypeError: no implicit conversion of Date into String
from /usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/dry-types-0.8.1/lib/dry/types/coercions.rb:11:in `parse'
```

The same is true for `Types::Form::DateTime` and `Types::Form::Time`, possibly others.

**Comment by solnic** [comment]
Closed via https://github.com/dry-rb/dry-types/commit/3043ba4e9345fff2545d69b5c1f8035dddadd22d
