### ISSUE TITLE
Embedded Value like in virtus?

### ISSUE THREAD

**Issue by rkrdo** [dry-rb/dry-types#145]
Is it possible to use an existing object as an attribute like in [virtus](https://github.com/solnic/virtus#embedded-value)?

**Comment by solnic** [comment]
Yes, what type of an object?

**Comment by rkrdo** [comment]
Something like the following example on the Virtus [README](https://github.com/solnic/virtus#embedded-value)

```ruby
module Types
  include Dry::Types.module
end

class City < Dry::Types::Struct
  include Types

  attribute :name, Types::String
end

class Address < Dry::Types::Struct
  include Types

  attribute :street,  Types::String
  attribute :zipcode, Types::String
  attribute :city,    City # how can a City object be defined?
end

```

**Comment by solnic** [comment]
Yes this is supported by dry-struct
