### ISSUE TITLE
surprising behaviour of subclassed structs when used as type in another struct

### ISSUE THREAD

**Issue by andreaseger** [dry-rb/dry-types#146]
So given this example:

``` ruby
require 'bundler/inline'
gemfile true do
  gem 'dry-types'
end

include Dry::Types.module

class A < Dry::Types::Struct
  attribute :a, Strict::Int
end

class AA < A
  attribute :aa, Strict::Int
end

class AB < A
  attribute :ab, Strict::Int
end

class Foo < Dry::Types::Struct
  attribute :bar, A
end


a = A.new(a: 123)
aa = AA.new(a: 123, aa: 234)
ab = AB.new(a: 123, ab: 345)

foo = Foo.new(bar: a)
p [ foo.bar.class,
    foo.bar.is_a?(A),
    foo.bar.is_a?(AA),
    foo.bar.is_a?(AB) ]
# [A, true, false, false]
# everything as expected

foo = Foo.new(bar: aa)
p [ foo.bar.class,
    foo.bar.is_a?(A),
    foo.bar.is_a?(AA),
    foo.bar.is_a?(AB) ]
# [A, true, false, false]
# hmm the type checking worked with subclasses
# but the attribute got somehow coerced? typecasted? type-assigned to it's parent class

foo = Foo.new(bar: ab)
p [ foo.bar.class,
    foo.bar.is_a?(A),
    foo.bar.is_a?(AA),
    foo.bar.is_a?(AB) ]
# [A, true, false, false]
# same as with AA
```

First of even though I don't remember reading it explicitly using a `Dry::Types::Struct` or `Value` as Type of an attribute in another `Struct` or `Value` works (almost) as expected.

The type itself is checked as expected and even stuff like `.optional` just works.

What surprised me is how subclassed `Struct`/`Values` are handled. As can be seen in the above example class `A` has two subclasses `AA` and `AB`. The type checking is done as expected meaning that the subclasses are valid too. But afterwards the attribute is no longer of the same type as the input value. So some form of type-casting/-coersion/-assignment is happening.

Is this a "weird" side-effect from something in the struct code or intended behaviour?

Right now my workaround is to use a sum type with all subtypes instead of the parent type but that only works because right now I have a very limited number of subtypes.

**Comment by solnic** [comment]
We moved `Struct` and `Value` to dry-struct project. Could you verify if this is happening with dry-struct too?

**Comment by solnic** [comment]
This issue was moved to dry-rb/dry-struct#14
