### ISSUE TITLE
`Dry::Types::Sum` and descendants lack `primitive` implementation

### ISSUE THREAD

**Issue by am-kantox** [dry-rb/dry-types#151]
I need to instantiate a constructor for `strict.bool` type and I am doing that way:

```ruby
::Dry::Types::Constructor.new(::Dry::Types['strict.bool'], fn: ->(v) do ... end)
```

The above leads to:

> NoMethodError: undefined method `primitive' for #<Dry::Types::Sum::Constrained:0x00000000efc630>

although [AFAIU] it should return `::Dry::Types['bool']`. I am currently fine with monkeypathing `Dry::Types::Sum::Constrained`:

```ruby
Dry::Types::Sum::Constrained.prepend(Module.new do
  def primitive
    case
    when [left, right].map(&:type).map(&:primitive) == [TrueClass, FalseClass]
      ::Dry::Types['bool']
    end
  end
end)
```

but I believe it makes sense to explicitly set the primitive for at least `strict.bool` type. since it’s already handled explicitly in `lib/dry/types/core.rb:63`.

**Comment by solnic** [comment]
sums can't respond to `primitive` since they have more than 1 primitive. If you want to define a constructor please use `Type#constructor` interface, ie something like this:

``` ruby
t = Types::Strict::Bool.constructor { |v| v == '1' }
t['1'] # true
t['fafsa'] # false
```
