### ISSUE TITLE
Doc update needed after dry-struct extraction

### ISSUE THREAD

**Issue by ehannes** [dry-rb/dry-types#152]
After you extracted Dry::Types::Struct into a separate gem, the documentation page [Struct & Value](http://dry-rb.org/gems/dry-types/struct-and-value/) needs an updated. For instance, the following class definition is no longer correct:

`class User < Dry::Types::Struct`

**Comment by backus** [comment]
Yeah I need to add docs for these soon.

**Comment by flash-gordon** [comment]
This was addressed a year ago :)
