### ISSUE TITLE
Discussion: Type identity

### ISSUE THREAD

**Issue by Kukunin** [dry-rb/dry-types#153]
Inspired by typing system in F# (I believe it's the same as in Haskell). I like the idea to express invariants and intention using types. It makes code explicit. 

For example:

``` fsharp
type ADiscriminatedUnionType = 
    | Alternative1 of int * string 
    | Alternative2 of bool 
    | Alternative3

//somewhere else
let f du =  
    // pattern matching 
    match du with 
    | Alternative1(x,s) -> printfn "x is %d, s is %s" x s 
    | Alternative2(b) -> printfn "b is %A" b 
    | Alternative3 -> printfn "three"
```

`SUM` supported by `dry-types` looks similarly, but it has one flow - you can't tell what type this specific object is.

``` ruby
CustomerID = Types::Strict::String
PostID = Types::Strict::String
some_id = CustomerID['abc']
# no way to tell either some_id is CustomerID or PostID
```

Even more problem, technically `CustomerID` and `PostID` are the same objects

``` ruby
CustomerID.object_id == PostID.object_id # true
```

I believe, that ruby is flexible and powerful enough, to make this possible within `dry-types`.
Let's discuss the best way to implement it. 

**My option:** 

We can define singleton method for every object that were passed via types constructor (e.g. `CustomerID['abc']`), which will return original type it was created with.

Then we can check:

``` ruby
case some_id.original_type
when CustomerID
...
when PostID
...
end
```

To workaround the same `object_id` problem, the most easier way is to use `#dup`

``` ruby
CustomerID = Types::Strict::String.dup
PostID = Types::Strict::String.dup
```

**Comment by Kukunin** [comment]
One more concern that should be implemented within scope of this issue is 

```ruby
post_id = PostID['123']
CustomerID[post_id] # exception, wrong type
```

Currently, with a regular string - it passes without any problem.

And one more concern: should we treat derived types as identity as well

```ruby
ConstrainedPostID = PostID.constrained(min_size: 5)
post_id = ConstrainedPostID['abcdef']
# is post_id === PostID ? 
```

**Comment by flash-gordon** [comment]
Types can be distinguished with meta if needed. In fact, type equality is crucial for many applications of `dry-types` so this definitely won't change anytime soon. There is a related proposal in https://github.com/dry-rb/dry-types/issues/92 which seems to be more promising and allows to distinguish either types and values in a more elegant and safe way (keep in mind you can't have a singleton class for integers, symbols, and frozen objects).
