### ISSUE TITLE
dry-struct dependency in gemspec?

### ISSUE THREAD

**Issue by dnd** [dry-rb/dry-types#154]
`Dry::Types::Struct` was recently extracted to `dry-struct` as `Dry::Struct`, but `dry-struct` doesn't appear to be listed as a runtime dependency in the gemspec, so it doesn't get installed when installing types. Should it be a dependency, or is it required to be manually included?

**Comment by flash-gordon** [comment]
Hi! `dry-struct` depends on `dry-types`, not vice versa, hence we can't have such a dependency in `dry-t`
