### ISSUE TITLE
Neither nil or None can be defaults for optional types

### ISSUE THREAD

**Issue by davidpelaez** [dry-rb/dry-types#155]
Consider an attribute like this in a struct:

`attribute :nickname, Types::Strict::String.maybe`

I would like that the default for that would be to have no nickname at all. I tried these two and they don't work:

```
Types::Strict::String.maybe.default(nil)
Types::Strict::String.maybe.default(Dry::Monads::Maybe::None.new)
```

How do I indicate that the default is to have no value? I don't see a reason for this to be forbiggen and I haven't been able to find a way to solve it. I posted in discuss about [how to create custom types](https://discuss.dry-rb.org/t/how-to-create-custom-types-with-validation-contraints-and-or-coercion/128) but got no answer. My intention was to define a custom `Maybe` type that would also accept that `nil` or a `None` as default but I haven't been able to find that workaround.

One reason why I think this should work is that this works `Types::Strict::String.maybe[Dry::Monads::Maybe::None.new]` so `Types::Strict::String.maybe.default Dry::Monads::Maybe::None.new` should work as well. 

*To put in simply any valid value of a type should be a valid default.*

This is an issue here in the types gem but it's actually affecting my usage of dry-struct because I cannot have a maybe field with defaults where the default is no value so I always have to pass `nickname: nil` and cannot take advantage of `constructor_type(:strict_with_defaults)`

Am I missing a proper way to use this or is it indeed a bug?

**Comment by flash-gordon** [comment]
Thanks for reporting this, I think it's a bug so I'll fix it
