### ISSUE TITLE
Types::Maybe::Int undefined but Types::Maybe::Strict::Int is.

### ISSUE THREAD

**Issue by georgemillo** [dry-rb/dry-types#163]
The [current docs for dry-types](http://dry-rb.org/gems/dry-types/optional-values/) use `Types::Maybe::Int` in a code example, but that type doesn't actually exist:

```ruby
require 'dry-types'
Dry::Types.load_extensions(:maybe)
module Types; include Dry::Types.module; end
Types::Maybe::Int # raises NameError: uninitialized constant #<Module:0x007f8f7b084b40>::Int
```

`Types::Maybe::Strict::Int` and `Types::Maybe::Coercible::Int` do exist though. Likewise for `String`, `Float`, etc.

I've [fixed](https://github.com/dry-rb/dry-rb.org/pull/114/files#diff-fe5cab2da123c6a5e647a73c75b85831L9) the docs as part of a larger PR, but is this a bug? Since `Types::Int` and `Types::Strict::Int` both exist, it makes sense that `Types::Maybe::Int` and `Types::Maybe::Strict.int` should both exist. And `Types::Int.maybe` doesn't raise an error.

**Comment by solnic** [comment]
That's a bug. We should have `Types::Maybe::Int` available. @flash-gordon looks like we forgot about defining them by default during extension-related refactor?

**Comment by flash-gordon** [comment]
@solnic should we? Seems like we didn't have them actually https://github.com/dry-rb/dry-types/blob/1bb113e9f1aa7ec15894d653daf0cf54139e7d1a/lib/dry/types/core.rb#L42-L50
```ruby
~/dev/dry-types [(1bb113e...)] $ ./bin/console
2.3.1 :001 > Types
 => Types
2.3.1 :002 > Types::Maybe::Int
NameError: uninitialized constant #<Module:0x007f906b019db8>::Int
	from (irb):2
	from ./bin/console:18:in `<main>'
2.3.1 :003 >
```

**Comment by solnic** [comment]
@flash-gordon oooh for some reason I thought it was there :/ OK, then in that case it's a mistake in the docs indeed :)

**Comment by georgemillo** [comment]
Leaving aside considerations about `Maybe`, I'm confused about what the non-strict, non-coercible types are actually supposed to do?

```
require 'dry-types'
require 'dry-struct'

class MyClass < Dry::Struct
  attribute :foo,  Dry::Types['nil']
  attribute :bar,  Dry::Types['class']
  attribute :buzz, Dry::Types['string']
end

x = MyClass.new(foo: 'not nil', bar: 'not a class', buzz: :not_a_string)
# => #<MyClass foo="not nil" bar="not a class" buzz=:not_a_string> 
x.foo
# => "not nil" 
x.bar
# => "not a class" 
x.buzz
#  => :not_a_string 
```

What advantage does the above code have over just using `attr_accessor`?

**Comment by solnic** [comment]
@georgemillo it's gonna raise when you pass attributes with missing keys, and you also may inspect its schema for...whatever purpose you may have, like maybe generate a html form from it etc.

**Comment by solnic** [comment]
> I'm confused about what the non-strict, non-coercible types are actually supposed to do

This is a common question. We should have that documented properly. Plain type definitions work as annotations. Their only behavior is to provide information about types, nothing else. A good example of its usage is rom-rb and its relation schemas, where dry-types are used to describe relation attributes. Notice that types support `Definition#meta` interface, which allows you to store *any* information you want, for instance in rom-sql we define `SQL::Types::Serial` and it's marked as `:primary_key` using this interface.

**Comment by georgemillo** [comment]
Okay, that makes sense. So in that case I suppose it wouldn't make much sense to provide `Types::Maybe::Int` because `Types::Int` accepts `nil` anyway, am I right?

**Comment by georgemillo** [comment]
To add to the above, if we accept that `Types::Maybe::Int` shouldn't exist, it would make sense for `Types::Int.maybe` to raise an error - but it currently doesn't. These two pieces of syntax should be made consistent.

**Comment by flash-gordon** [comment]
@georgemillo this is different. You can create as many types as you like by calling methods from [Builder](https://github.com/dry-rb/dry-types/blob/master/lib/dry/types/builder.rb) but it doesn't mean every such type gets a constant in `Dry::Types`.

**Comment by georgemillo** [comment]
Ah, okay, I get it.

I think that resolves this then. The mistake in the docs is already fixed in https://github.com/dry-rb/dry-rb.org/pull/114/ so I'll finish up the rest of that PR asap.
