### ISSUE TITLE
undefined method `const_set' for certain namespaces

### ISSUE THREAD

**Issue by georgemillo** [dry-rb/dry-types#168]
This works fine:

```ruby
require 'dry-types'

Dry::Types.register(
  'stripped.string',
  Dry::Types['string'].constructor { |*args| String(*args).strip },
)

module Types
  include Dry::Types.module
end
```

But this raises an error (note I'm now trying to define `string.stripped` rather than `stripped.string`):

```ruby
require 'dry-types'

Dry::Types.register(
  'string.stripped',
  Dry::Types['string'].constructor { |*args| String(*args).strip },
)

module Types
  include Dry::Types.module
end

dry-types-0.9.0/lib/dry/types.rb:90:in `block in define_constants': undefined method `const_set' for #<Dry::Types::Definition primitive=String options={}> (NoMethodError)
	from dry-types-0.9.0/lib/dry/types.rb:85:in `map'
	from dry-types-0.9.0/lib/dry/types.rb:85:in `define_constants'
	from dry-types-0.9.0/lib/dry/types.rb:30:in `module'
```

Is this a bug, or a feature? I'd like it if `String::Stripped` is possible as a type name as this makes more sense to me than `Stripped::String` ('stripped strings' are a subset of 'strings' and I can't thing of another type for which the idea of 'stripping' it would make sense.)

If you don't want 'string.*' to be possible as a type name, can the error be made more intuitive? Note that it isn't raised when you *define* the type, but when you *include* `Types.module` into another module later on - very unintuitive.

Perhaps a more general solution (which isn't incompatible with making 'string.stripped' a valid name) would be to get clear on which type names are acceptable and which aren't, and to validate type names on `register`. Something like this regex as a first approximation? `/\A[a-z]+(\.[a-z]+)*\z/`?

I'm happy to tackle this one myself; just want to clarify what the desired behaviour is.

**Comment by solnic** [comment]
Why not just:

``` ruby
module Types
  module String
    Stripped = ...
  end
end
```

?

**Comment by georgemillo** [comment]
I guess that could work, but why not allow passing names like `string.whatever` to `register` on a more general note?

Is it recommended to register my own types with `Dry::Types.register`, or is defining my own constants like in your example the preferred way? (Is there any reason to favour one over the other?)

I still think it's a good idea to raise an error message in `register` if it's passed an invalid string rather than letting it accept a time bomb which will explode later. A general criticism I have of the Dry libraries is that they tend to raise very cryptic error messages when I get something wrong and I have to go digging around in the source code (or pester someone in gitter or here ;) ) to figure out how to fix it. Again, I'm happy to help and add better error handling, just making sure that I'm adding the right thing.

**Comment by flash-gordon** [comment]
@solnic it seems we'd rather keep this API private since I see no reason to use it. I saw some people complain about the verbosity of things like `Types::String::Whatever` over `'string.whatever'` when using them with structs. I agree to some extent but strings are primitives and lack of DSL so I'd stick to provide a single API.

**Comment by solnic** [comment]
@flash-gordon which API? `register`?

**Comment by flash-gordon** [comment]
yep

**Comment by solnic** [comment]
yes this shouldn't be used, constant assignment is how people should be defining their own types
