### ISSUE TITLE
Documentation question: Types::Json

### ISSUE THREAD

**Issue by Lukkor** [dry-rb/dry-types#171]
Hello,

This [page](http://dry-rb.org/gems/dry-types/built-in-types/) makes reference to multiple JSON types which does not appear to exist (e.g. Types::Json::Int).
Do I miss something or is this a problem in the documention?

**Comment by solnic** [comment]
It's a mistake in the docs :(

**Comment by Lukkor** [comment]
I open a pull request on the documentation repository:
https://github.com/dry-rb/dry-rb.org/pull/122
