### ISSUE TITLE
Passing predicates to a constrained type builder

### ISSUE THREAD

**Issue by faucct** [dry-rb/dry-types#179]
Hello, if I want to create a constrained type with a custom predicate then I have to register it inside `Dry::Logic::Predicates` as the type builder expects it to be found there - https://github.com/dry-rb/dry-types/blob/9bf72c8/lib/dry/types/constraints.rb.
It would be cool to make it possible passing unregistered predicates, like this - `Dry::Types::Strict::String.constrained(IpAddress::Predicate => true)`

**Comment by flash-gordon** [comment]
This is now possible using the `case?` predicate from dry-logic: https://github.com/dry-rb/dry-logic/blob/master/CHANGELOG.md#v042-to-be-released 
Anything that responds to `===` can be used, including strings, numbers, classes, ranges, regexes, and even procs. Does it suit you?
/cc @solnic did you know? :) I'd call it the predicate of last resort lol

**Comment by faucct** [comment]
I didn't know that procs respond to `===`. I guess it solves the problem. Thanks.

**Comment by solnic** [comment]
Yeah I knew. We can add an alias `last_resort?` ;)
