### ISSUE TITLE
Enforce that Object type is not nil

### ISSUE THREAD

**Issue by Fryie** [dry-rb/dry-types#183]
Disclaimer: Still new to the gem, might have missed something.

With https://github.com/dry-rb/dry-types/issues/123, an `Object` type was introduced. However, I don't currently see a way to enforce that what you pass in is not `nil`. For example, I have code to the following effect using dry-struct:
```
class MyValueObject < Dry::Struct::Value
  constructor_type :strict

  attribute :some_object_reference, Types::Object
end
```

but I'd like `MyValueObject.new` to fail, since it doesn't include the object reference.

Is there any way to make this happen? I realise that `Types::Object` just generally doesn't really give you a lot of type safety, but in this case I have existing objects that I'd like to reuse and not passing an argument to the constructor is one of these errors that I'd like to catch early.

**Comment by solnic** [comment]
Do you know all possible object types?

**Comment by Kukunin** [comment]
actually `Types::Something` doesn't provide any constraints (actually, this is pretty unobvious).
Try `Types::Strict::Object` which forces constraints.

BTW, @solnic is there good reason behind that `Types::Int['123']` doesn't fail?

**Comment by Fryie** [comment]
@Kukunin If I try `Types::Strict::Object` I get an error like:

> uninitialized constant #<Module:0x007fa3cdb92878>::Object

@solnic In theory yes. In practice, I have a unit test that constructs a `MyValueObject` instance but sends in test doubles since the real objects are expensive to construct. That would break if I constrained the class type. But maybe (very possibly) I'm doing it wrong?
I have tried to look at [dry-logic predicates](http://dry-rb.org/gems/dry-logic/predicates/). Maybe one of these (`filled?`?) could work, but I have so far been unsuccessful in finding out how to turn that predicate into a type constraint. `Types::Object.constrained(filled: true)` doesn't seem to enforce anything (is that related to what @Kukunin commented?).

**Comment by Kukunin** [comment]
ok. another attempt.

Did you know, that `nil.is_a?(Object)` is true? So, `nil` is an object itself. 
So, you need to clarify your constraint. 

you can achieve what you need with `Types::Object.constrained(excluded_from: [nil])`.
You can even hide this with something like

```
Types::NotNilObject = Types::Object.constrained(excluded_from: [nil]) 

class MyValueObject < Dry::Struct::Value
  constructor_type :strict

  attribute :some_object_reference, Types::NotNilObject
end
```

**Comment by Fryie** [comment]
@Kukunin that works :) ty!
