### ISSUE TITLE
Weird behaviour with `options` when defining an enum with a default

### ISSUE THREAD

**Issue by georgemillo** [dry-rb/dry-types#189]
I've spotted some weird behaviour when defining an enum with a default:

```ruby
require 'dry-types'

module Types
  include Dry::Types.module
end

string = Types::Strict::String

default_first = string.default('foo').enum('foo', 'bar')
default_first.options
# => {:values=>["foo", "bar"]}
default_first.values
# => ["foo", "bar"]

default_last = string.enum('foo', 'bar').default('foo')
default_last.options
# => {}
default_last.values
# => NoMethodError Exception: undefined method `values' for #<Dry::Types::Default:0x007fdcaa82a170>
```

As you can see, calling `default` then `enum` works as expected, but calling `enum` then `default` means that the `options` hash won't be set correctly and `values` won't work.

It's not a big deal, because I can just use the 'default first' approach, but it's still unintuitive - I had no idea that the order mattered, and bugs resulted.

Not sure what the best way to fix this; I don't know enough about the internals of dry-types. Or maybe the problem's not worth fixing, in which case I think the docs should be updated to point out this pitfall. (Or `Enum#default` should raise an error and tell you to use `Default#enum` instead, rather than slyly returning a type that won't quite behave as expected.)

**Comment by solnic** [comment]
We should make `Enum#default` raise an error and explain it should be set first then the enum. Maybe we can make it work eventually but raising is the fastest solution for now.
