### ISSUE TITLE
Add single-value types

### ISSUE THREAD

**Issue by flash-gordon** [dry-rb/dry-types#197]
In some cases, you want to have a type that has a single instance. For example, Ruby's `TrueClass`, `FalseClass`,  and `NilClass` all have a single value `true`, `false`, and `nil` correspondingly. To make it more generic we can have something like this

```ruby
# uses .equal? in valid?
nil_type = Types::Constant(nil)
true_type = Types::Constant(true)

# uses .== in valid?
empty_list_type = Types::Value([])
```

This can be implemented with `Constrained` but maybe we need more predicates in dry-logic for that.

@solnic WDYT?

**Comment by solnic** [comment]
what'd be the difference between this and `Types::Strict::Nil` etc.?

**Comment by flash-gordon** [comment]
I don't mean any difference for existing types, but it would allow building app-level constant types, e.g.

```ruby
Success = Types::Constant('success')
Failure = Types::Constant('failure')

Result = Success | Failure

case result
when Success then # happy path
when Failure then # 
end
```
