### ISSUE TITLE
Inconsistent behavior between 0.9 and 0.10 with `constructor_type` schema

### ISSUE THREAD

**Issue by tpendragon** [dry-rb/dry-types#198]
Given the code:

```ruby
# frozen_string_literal: true
class RootClass < Dry::Struct
  constructor_type :schema
end
class BookTest < Dry::Struct
  attribute :id, Valkyrie::Types::ID.optional
  attribute :title, Valkyrie::Types::Coercible::Array
end
```

In 0.9.4 I get the following:

```ruby
[1] pry(main)> BookTest.new
=> #<BookTest id=nil title=[]>
[2] pry(main)> BookTest.new.title
=> []
```

That's perfect!

In 0.10.3 I get:

```ruby
[5] pry(main)> BookTest.new
Dry::Struct::Error: [BookTest.new] :id is missing in Hash input
from /Users/tterrell/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/dry-struct-0.3.0/lib/dry/struct/class_interface.rb:109:in `rescue in new'
```

If I move `constructor_type` down to BookTest, it initializes, but I get the following:

```ruby
[9] pry(main)> BookTest.new
=> #<BookTest id=nil title=nil>
[10] pry(main)> BookTest.new.title
=> nil
```

Defaults are no longer generated for properties that aren't passed in - which I thought was the purpose of the `schema` constructor_type. Is this a bug, or has the opinion of the library changed?

Thanks!

**Comment by backus** [comment]
There were breaking changes for hash schemas but that was from 0.9 being released https://github.com/dry-rb/dry-types/blob/master/CHANGELOG.md#changed-3

Have you looked at the different schema options? We intentionally added schemas which support defaults. See http://dry-rb.org/gems/dry-types/hash-schemas/

**Comment by tpendragon** [comment]
Ah - I think my issue here is I just misunderstood what defaults were. For some reason I thought it would pre-populate with whatever happens when you pass nil into the type. Looks like it used to - now I can just set defaults on my type definitions. Thanks!
