### ISSUE TITLE
Date, DateTime and Time coercions don't use built in to_type methods.

### ISSUE THREAD

**Issue by dr0verride** [dry-rb/dry-types#199]
Is there a reason that the Date, DateTime and Time coercions don't look for the built in to_date, to_datetime and to_time methods?

I recently needed to turn a Time type into a Date and I assumed that would happen with the built in coercions. As it stands now only objects that respond to to_str will result in a new Date object.

I am working on a pull request to add change these coercions to check for to_date & co., but I was wondering if there was a good reason to not include that functionality.

**Comment by solnic** [comment]
The reason is that they are not generic coercions, that's why we have separate coercion categories like `Form` and `JSON`. I don't think we'll ever have generic coercions like in virtus because it's too ambiguous and complex.

Anyhow, what's your use case? :)

**Comment by dr0verride** [comment]
My use case is that I have 2 data sources (AR relations) being mapped to one collection of Dry-Structs. In one source the column is a timestamp and in the other source it's a date. Since the field silently allowed the Datetime object through everything worked fine except for equality comparisons. The mixed content in the field made this particularly tricky to figure out. My solution was to change the type to be a `Strict::Date` and manually map over the field and convert it in my transform. 

After solving my problem and thinking on this some more I prefer the way I have things now to what I had in mind. In the long run I can see how having silent conversions could cause unexpected behavior. Especially when dealing with time.
