### ISSUE TITLE
Constrained strict types don't work on ruby 2.1.0

### ISSUE THREAD

**Issue by michalbugno** [dry-rb/dry-types#201]
Judging by https://github.com/dry-rb/dry-types/blob/master/dry-types.gemspec Ruby 2.1.X is supported.

### test case
```
require "dry-types"

include Dry::Types.module
string = Strict::String.constrained(min_size: 3)
p string['foo']
p string['fo']
```

### ruby 2.3.0
```
$ ruby test.rb
"foo"
"fo" violates constraints (min_size?(3, "fo") failed) (Dry::Types::ConstraintError)
```

This test case is a correct behaviour, type violation because `"fo"` is of size < 3

### ruby 2.1.0
```
$ ruby test.rb
"foo"
"fo"
```

There is no exception raised here, incorrect behaviour.

Am I missing something here?

Thanks for help!

**Comment by solnic** [comment]
We don't support ruby 2.1.0, and I suppose we need to update gemspec to reflect that.

**Comment by michalbugno** [comment]
I guess this should be the next step then, thanks for clarification! :)

**Comment by flash-gordon** [comment]
@michalbugno done then 😬 

@solnic looks like we need to establish minimal version updates as a one more maintainer routine

**Comment by solnic** [comment]
@flash-gordon I know...I think we're missing this version spec in most of the gemspecs :/

**Comment by flash-gordon** [comment]
@solnic yes, we are, however most of things depend on dry-core which currently has `>= 2.1.0`
