### ISSUE TITLE
Use meta on self defined objects

### ISSUE THREAD

**Issue by lal-s** [dry-rb/dry-types#209]
I want to add meta data to my attributes. For example, I have the following classes: 

```
class User < Dry::Struct
  attribute :name, Types::String.meta(my_meta: 'meta'
  attribute :address, Address
  attribute :accounts, Types::Array.member(Account).meta(resource: 'my resource')
end

class Address < Dry::Struct
  attribute :street, Types::String
  attribute :city, Types::String
end

class Account < Dry::Struct
  attribute :account_num, Types::Int
end
```
 I want to be able to add meta data to attribute `address` in `User`, is there  a way to do it?
i.e

```
attribute :address, Address.meta(my_meta: 'meta')
```

Probably if I can define it differently eg: `attribute :address, Types::Address.meta(my_meta: 'meta')` just so that it lets me use meta on it.

**Comment by solnic** [comment]
This issue was moved to dry-rb/dry-struct#47
