### ISSUE TITLE
Should there be a Types::Coercible::Bool ?

### ISSUE THREAD

**Issue by awead** [dry-rb/dry-types#217]
I was expecting there to be a `Types::Coercible::Bool` but didn't find one. Maybe there's a reason for that? I'm recent to the dry-ruby world, so apologies if this is a stupid question. I was thinking something simple like:

``` ruby
>  struct.boolean = "false"
=> false
>  struct.boolean = "true"
=> true
>  struct.boolean = "foo"
=> Dry::Types::ConstraintError
```

**Comment by flash-gordon** [comment]
Coercible types use methods from `Kernel` like `Integer()`, `Float()` and so on, there is no built-in coercion for booleans hence no such a type in dry-types. You can use `Types::Form::Bool` or build your own type with `Types::Bool.constructor { |input| ... }`

**Comment by pnomolos** [comment]
@flash-gordon I realize the reasoning behind closing this issue, but may I suggest that `Types::Coercible::Bool` would use what is effectively the built-in conversion of just `!!value`?  That is:

```ruby
Types::Coercible::Bool = Types::Bool.constructor { |value| !!value }
```

This makes everything but `nil` and `false` a true value.  I appreciate that it's not using the same built-in coercions such as `Integer()` and `Float()` but I feel that it's close enough, perhaps?

**Comment by solnic** [comment]
@pnomolos that's too broad, we definitely do not want such a generic coercion mechanism. If you have a use case like that, just define your own type, which as you showed is very simple to do 😄

**Comment by colszowka** [comment]
In our similar case we wanted to mirror the behaviour ActiveRecord has, particularily for coercing form checkboxes etc., so based on @pnomolos suggestion we expanded that to use active models boolean coercion:

```ruby
# frozen_string_literal: true

module Types
  include Dry::Types.module

  Coercible::Bool = Types::Bool.constructor do |value|
    ActiveRecord::Type::Boolean.new.serialize value
  end
end

```

**Comment by proton** [comment]
Try `Types::Params::Bool`
