### ISSUE TITLE
Rename `Types::Json` => `Types::JSON`

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-types#218]

**Comment by ndrluis** [comment]
@solnic I think that's already done only the documentation is outdated.

I can solve this 😄

**Comment by solnic** [comment]
I don't think it is:

```
∞ [ruby-2.4.1][node-v7.3.0] dry-types git(master) ✗ bin/console
irb(main):001:0> Types::JSON
NameError: uninitialized constant Types::JSON
Did you mean?  Types::Json
```

**Comment by andriytyurnikov** [comment]
Looks like this is where metaprogramming with strings fights back.
Trick is that underscore and camelize are not reverse equvalents of each other
`Inflecto.underscore("JSON") # "json"` 
but 
`Inflecto.camelize('json') # "Json" not "JSON" `
I would humbly suggest to stick with "Json"
Visible alternatives here "purism" - changing global stance on naming and strings, or some customized "smart" inflection

**Comment by timriley** [comment]
I think we should keep it as `JSON`. It’s the right way to refer to the acronym, and it’s consistent with other Ruby libraries like `Net::HTTP`. The fact that string constantizing has led Rubyists to use poorly formatted acronyms across their apps is IMHO an antipattern and we I don’t think we should degrade our own naming to support it :)

**Comment by solnic** [comment]
We need to wait with this until dry-inflector is ready, and we switched to using it in dry-types.

**Comment by andriytyurnikov** [comment]
@timriley , idea of supporting abbreviations "properly" is attractive indeed, JSON, HTTP, GraphQL, etc., a lot of those used in programming.
I just wanted to highlight possible need for fundamental change naming/AST to achieve such outcome. Downcasing by definition is an algorithm with irreversible loss of information - no inflector could change that.
So one might want want to consider using consistent type names without transformations through all layers.
