### ISSUE TITLE
Type Sum doesn't work with custom constructor

### ISSUE THREAD

**Issue by vmeyet** [dry-rb/dry-types#243]
#### Issue

When using a custom constructor (`#constructor` method) and using Type sum (`|` operator) the strictness/coercition doesn't work.

#### How to reproduce

```ruby
module DryTypes
    include Dry::Types.module
end


DryTypes::Strict::String.constructor(&:itself)[1]
# Dry::Types::ConstraintError
DryTypes::Strict::Nil[1]
# Dry::Types::ConstraintError

# The following work as expected
(DryTypes::Strict::String | DryTypes::Strict::Nil)[1]
# Dry::Types::ConstraintError

# The following should raise an exception
(DryTypes::Strict::String.constructor(&:itself) | DryTypes::Strict::Nil)[1]
# => 1
```

#### Versions

ruby: 2.5.0
dry-types: 0.12.2

**Comment by vmeyet** [comment]
As a workaround you can do the following

```ruby
(DryTypes::Strict::String | DryTypes::Strict::Nil).constructor(&:itself)[1]
# Dry::Types::ConstraintError
```

But that doesn't help much composability

**Comment by GustavoCaso** [comment]
@vmeyet I will have a look.  Thanks for opening the issue ❤️

**Comment by fledman** [comment]
I can't reproduce at HEAD, so I guess it was already fixed?
```ruby
2] pry(main)> (DryTypes::Strict::String.constructor(&:itself) | DryTypes::Strict::Nil)[1]
Dry::Types::ConstraintError: 1 violates constraints (type?(NilClass, 1) failed)
```

**Comment by GustavoCaso** [comment]
@vmeyet I have been testing in master and seem to be working just fine.

I had this test running and it was working.

```ruby
it 'works with constructor' do
      left = Dry::Types['strict.string'].constructor(&:itself)
      right = Dry::Types['strict.nil']

      type = left | right

      expect {
        type[1]
      }.to raise_error(Dry::Types::ConstraintError)
    end
```

Also, an output from my terminal 

```
(Types::Strict::String.constructor(&:itself) | Types::Strict::Nil)[1]
Dry::Types::ConstraintError: 1 violates constraints (type?(NilClass, 1) failed)
```

I will close the ticket. Also @fledman thanks for having a look as well.

**Comment by vmeyet** [comment]
Thanks for you fast answers, when do you think a version with the fix will be released?

**Comment by vmeyet** [comment]
for information the fix has been introduced by https://github.com/dry-rb/dry-types/commit/c2fd188915dd097b15757de3397a4675060dead8 :)
