### ISSUE TITLE
.optional not considered for Array of Hashes

### ISSUE THREAD

**Issue by brentdodell** [dry-rb/dry-types#247]
I'm not sure if this is a bug, feature request, or if I'm just doing something incorrectly. I'm trying the following:

```Ruby
hash = {
  title: 'Test Title',
  links: [
    {
      text: 'Link Text',
      url: 'example.com'
    },
    {
      text: 'Link 2',
      url: 'test.org'
    }
  ],
}

shape = Types::Hash.strict_with_defaults(
  title: Types::Strict::String,
  links: Types::Strict::Array.of(
    Types::Hash.strict(
      text: Types::Strict::String,
      url: Types::Strict::String,
    ),
  ).optional,
)

shape[hash]
```

My goal is to get an error if **title**, **text**, or **url** is not a `String`, if **title** is missing (`nil` value or the key doesn't exist), or if **links** isn't an array of hashes in the shape I expect.

There should be no error though if **links** is `nil` or the key doesn't exist, because it's `optional`.

### Should be Valid

```Ruby
hash = {
  title: 'Test Title',
  links: [
    {
      text: 'Link Text',
      url: 'example.com'
    },
    {
      text: 'Link 2',
      url: 'test.org'
    }
  ],
}
```

```Ruby
hash = {
  title: 'Test Title',
  links: [
    {
      text: 'Link Text',
      url: 'example.com'
    }
  ],
}
```

```Ruby
hash = {
  title: 'Test Title',
  links: nil,
}
```

```Ruby
hash = {
  title: 'Test Title',
}
```

### Should be Invalid

`title: nil`
```Ruby
hash = {
  title: nil,
  links: [
    {
      text: 'Link Text',
      url: 'example.com'
    },
    {
      text: 'Link 2',
      url: 'test.org'
    }
  ],
}
```

`title:` missing
```Ruby
hash = {
  links: [
    {
      text: 'Link Text',
      url: 'example.com'
    },
    {
      text: 'Link 2',
      url: 'test.org'
    }
  ],
}
```

`title:` non-string
```Ruby
hash = {
  title: 1,
  links: [
    {
      text: 'Link Text',
      url: 'example.com'
    },
    {
      text: 'Link 2',
      url: 'test.org'
    }
  ],
}
```

`link: { text: }` non-string 
```Ruby
hash = {
  title: 'Test Title',
  links: [
    {
      text: 1,
      url: 'example.com'
    }
  ],
}
```

`link: { text: }` nil
```Ruby
hash = {
  title: 'Test Title',
  links: [
    {
      text: nil,
      url: 'example.com'
    }
  ],
}
```

`link: { text: }` missing
```Ruby
hash = {
  title: 'Test Title',
  links: [
    {
      url: 'example.com'
    }
  ],
}
```

`link: { url: }` non-string 
```Ruby
hash = {
  title: 'Test Title',
  links: [
    {
      text: 'Link',
      url: 1
    }
  ],
}
```

`link: { url: }` nil
```Ruby
hash = {
  title: 'Test Title',
  links: [
    {
      text: 'Link',
      url: nil
    }
  ],
}
```

`link: { url: }` missing
```Ruby
hash = {
  title: 'Test Title',
  links: [
    {
      text: 'Link',
    }
  ],
}
```

Thanks!

**Comment by brentdodell** [comment]
I know this is a different library, but I believe I was able to achieve what I was looking for with the following in `dry-validation`, I just don't get the errors raised like I did with `dry-types`. (with `hash` being the values above)

```Ruby
shape = Dry::Validation.Schema do
  required(:title).filled(:str?)
  optional(:links).each do
    schema do
      required(:text).filled(:str?)
      required(:url).filled(:str?)
    end
  end
end

shape.(hash)
```

**Comment by flash-gordon** [comment]
@brentdodell this was solved by replacing hash schemas with a new API in https://github.com/dry-rb/dry-types/pull/231. Please, next time use GH only for confirmed bugs or approved feature requests, post to [the forum](https://discourse.dry-rb.org) or ask on [the gitter channel](https://gitter.im/dry-rb/chat).

**Comment by flash-gordon** [comment]
🤔 though, I agree, it might look like a bug to you. Anyhow, post to the forum it you're not sure, we're following :)

**Comment by brentdodell** [comment]
Thank you @flash-gordon. I wasn’t aware of the forum or gitter channel. I think I also opened an issue in dry-validations that probably belonged in one of those places as well.

**Comment by flash-gordon** [comment]
These are in our contributing guidelines, check them out https://github.com/dry-rb/dry-types/blob/master/CONTRIBUTING.md :)
