### ISSUE TITLE
Confusing message in output

### ISSUE THREAD

**Issue by faun** [dry-rb/dry-types#260]
When I start my app that uses dry-types (via dry-validation), I see the following message:

```
[dry-types] Int type was renamed to Integer
[dry-types] Form types were renamed to Params
```

It's not clear the impact of this change, the required remediation action (if any) or if there's a way to silence this output.

Is there anything I need to do? My tests all still pass, so is there a way to make this message go away?

Thanks!

**Comment by faun** [comment]
These are the versions I'm using:

```
dry-configurable 0.7.0
dry-container 0.6.0
dry-core 0.4.7
dry-equalizer 0.2.1
dry-inflector 0.1.2
dry-logic 0.4.2
dry-types 0.13.2
dry-validation 0.12.0
dry-validation-matchers 0.4.1
```

**Comment by abrthel** [comment]
These changes are noted in the project changelog located [https://github.com/dry-rb/dry-types/blob/master/CHANGELOG.md](https://github.com/dry-rb/dry-types/blob/master/CHANGELOG.md)

Anywhere you are using `Types::Strict::Int` or similar needs to be replaced with `Types::Strict::Integer` and likewise any where you use `Types::Form::*` types need to be updated to `Types::Params::*`

I'm not sure why your tests are passing though as to keep the old behavior you need to opt in.

**Comment by flash-gordon** [comment]
This is a bug in dry-validation revealed after a fix in dry-core, see https://github.com/dry-rb/dry-validation/issues/413
