### ISSUE TITLE
Constraints ignored in schema fields

### ISSUE THREAD

**Issue by bjeanes** [dry-rb/dry-types#261]
I'm not sure if I have the terminology consistent with that of the gem, so a code example may best serve to explain what seems like a bug to me:

``` ruby
Dry::Types::VERSION # => "0.13.2"

Types = Dry::Types.module
Types::ID = Types::Params::Integer.constrained(gt: 0)
Types::Record = Types::Params::Hash.schema(id: Types::ID)

Types::ID[-1] # => Dry::Types::ConstraintError: -1 violates constraints (gt?(0, -1) failed)
Types::Record[{id: -1}] # => {id: -1}
```

I'd expect that last line to raise a `Dry::Types::ConstraintError`, instead of accepting `-1`, which violates the constraint associated with the type assigned to the `id` field of the schema.

**Comment by solnic** [comment]
`Params` is designed specifically to allow failures like Gustavo mentioned. Use `try` if you want to check for failures or use `Strict` types if you want exceptions. If you want to *validate* input do not use dry-types, use dry-schema instead (or dry-validation if you need more advanced validation support).
