### ISSUE TITLE
Tuples / hash key type definitions?

### ISSUE THREAD

**Issue by idrozd** [dry-rb/dry-types#262]
Great job! Thank you.
Looks like ruby can use some types after all ;)

Just wondering, how does one define a tuple type with dry-types?

Or, maybe, some way to define type for keys in hash?

To provide specific example, I need some way to define type for collection of users and their corresponding sets of calendar events to calculate intersections.
Existing code expects data to be hash of {user => that_users_events}, so that's what I want ideally )

**Comment by GustavoCaso** [comment]
For questions please use discourse.dry-rb.org

We also have the http://dry-rb.org with documentation. You can try looking at here http://dry-rb.org/gems/dry-types/hash-schemas/
