### ISSUE TITLE
weird behavior

### ISSUE THREAD

**Issue by schmurfy** [dry-rb/dry-types#263]
I just stumbled on a weird issue with version 0.13.2:

```ruby
require 'dry-types'
Dry::Types.module()::JSON::Time.valid?("2018-05-25T14:29:20+00:00") # => false
Dry::Types.module()::JSON::Time["2018-05-25T14:29:20+00:00"].class # => Time
```

I am not sure where the bug is but it should not tell be the value is invalid when the conversion works, did I miss something ?

**Comment by GustavoCaso** [comment]
@schmurfy `valid?` check if the value is a `primitive` in this case `Time`, so if you try:
```ruby
Dry::Types.module()::Time.valid?("2018-05-25T14:29:20+00:00") # => false
```

Now when you try to use `::JSON::Time["2018-05-25T14:29:20+00:00"]` it will try to convert using coercions https://github.com/dry-rb/dry-types/blob/master/lib/dry/types/coercions.rb#L36

**Comment by schmurfy** [comment]
ok I think I get it, I stopped using dry-types it simply does not do what I wanted it to so this issue cna be closed is the behavior is "normal".
