### ISSUE TITLE
Coercing from a timestamp does not work (should it?)

### ISSUE THREAD

**Issue by mensfeld** [dry-rb/dry-types#266]
Not sure if a bug or a feature. I have a timestamp in an int that does not get converted to anything.

```
time = '1529884800'
Dry::Types.module()::JSON::Time.valid?(time) #=> false
Dry::Types.module()::JSON::Time[time] #=>  '1529884800'
```
The only way it can work, is by doing something like that:

```
MyTime = Types::Params::Time.constructor { |val| ::Time.at(val.to_i) }
```

**Comment by GustavoCaso** [comment]
@mensfeld Looks like is the expected behavior, in the coercion https://github.com/dry-rb/dry-types/blob/master/lib/dry/types/coercions.rb#L38 we use `Time.parse` and if an `ArgumentError` is raised we return the input, in this case, is what is happening:

```ruby
Time.parse('1529884800')
ArgumentError: argument out of range
```

**Comment by mensfeld** [comment]
So it is a feature.
