### ISSUE TITLE
Params to_decimal first casts to Float

### ISSUE THREAD

**Issue by JanStevens** [dry-rb/dry-types#268]
Params `to_decimal` method first cast to_float which loses precision, rather the implementation of Json should be followed

https://github.com/dry-rb/dry-types/blob/master/lib/dry/types/coercions/params.rb#L56

This would also mean that to decimal can be lifted and added to core Coercions class (instead of two different implementations for JSON and Params)

Also the spec that tests for not losing precision is flawed (https://github.com/dry-rb/dry-types/blob/master/spec/dry/types/types/params_spec.rb#L219). Following example demonstrates this better (assuming a string with long precision is given)

```ruby
pry(main)> decimal = 23.to_d/7.to_d
=> 0.3285714285714285714e1
pry(main)> decimal = decimal.to_s
=> "3.285714285714285714"
pry(main)> Float(decimal)
=> 3.2857142857142856
pry(main)> Float(decimal) == decimal.to_d
=> false
```

Regards

**Comment by flash-gordon** [comment]
Yes, but it returns `input.to_d` i.e. doesn't reuse float so no precision is lost
```
[1] pry(main)> Types::Params::Decimal["3.285714285714285714"] == 23.to_d/7.to_d
=> true
```
