### ISSUE TITLE
uninitialized constant <Module:0x0055ba7a193270>::Integer

### ISSUE THREAD

**Issue by coding-bunny** [dry-rb/dry-types#272]
Hello,

I'm trying to include `dry-types` into our small Rails app for constructing some simple models to handle API responses. Basically parse JSON and transform it into actual objects to have an easier way.

I'm trying to get RSpec now to play nicely with this, but keep running into some issues when running the test.

* dry-types 0.12.3
* rspec-rails 3.8

Basically, I created  simple model like this:

```
module HiddenApi
  class Answer
    attribute :id, ::Types::Coercible::Integer
    attribute :response_text, ::Types::Strict::String.optional
    attribute :custom_responses, ::Types::Strict::Array.of(::Types::String::String)
  end
end
```

I have an initializer for Rails, to get the types going:

```
# config/initializers/dry_types.rb
# Initializer for dry-types.
# Configures the gems to make sure everything is properly loaded and working under the Rails environment.
require 'dry-types'
require 'dry-struct'

module Types
  include ::Dry::Types.module
end
```

Installed **rspec**, ran the `rails g rspec:install` command from the documentation and running pretty much the default configuration.
This is my spec:

```
require 'spec_helper'

require_relative '../../../config/initializers/dry_types'
require_relative '../../../app/models/hidden/answer'

::RSpec.describe ::Hidden::Answer do
  it 'properly coerces the values for it the id-attribute' do
    answer = described_class.new(id: '1')

    expect(answer.id).to(eql(1))
  end
end
```

Just wanted to add something basic like this to see it works as expected.
But this tosses me the following error:

```
An error occurred while loading ./spec/models/hidden/answer_spec.rb.
Failure/Error: attribute :id, ::Types::Coercible::Integer

NameError:
  uninitialized constant #<Module:0x0055ba7a193270>::Integer
# ./app/models/hidden/answer.rb:6:in `<class:Answer>'
# ./app/models/hidden/answer.rb:5:in `<module:Hidden>'
# ./app/models/hidden/answer.rb:4:in `<top (required)>'
# ./spec/models/hidden/answer_spec.rb:4:in `require_relative'
# ./spec/models/hidden/answer_spec.rb:4:in `<top (required)>'
No examples found.


Randomized with seed 662

Top 0 slowest examples (0 seconds, 0.0% of total time):

0 examples, 0 failures, 0 passed

Finished in 0.001762969 seconds


Randomized with seed 662

Process finished with exit code 1
Empty test suite.
```

I'm obviously missing something, and I can't wrap my head around it.
It's been a while since I set all this up from scratch, and I don't understand what's going wrong.
Followed the documentation for all involved gems as best as I could.

**Comment by flash-gordon** [comment]
The docs are up to date but they are for version 0.13. See the [changelog](https://github.com/dry-rb/dry-types/blob/b847b21ab5c84eb2eed545c7e0b919a64ff29ed5/CHANGELOG.md#changed) for changes.
