### ISSUE TITLE
Print a warning when default value isn't frozen

### ISSUE THREAD

**Issue by flash-gordon** [dry-rb/dry-types#279]
This occasionally happens that people think a default value won't be shared across type applications. That's not the case. It could be avoided through the use of `.dup` on values but I argue it's not always safe, rather I'd print a warning that the provided value isn't frozen. Also, for cases when it's fine for some reason, I'd have a `shared` keyword that would discard the warning.
```ruby
Types::Strict::String.default('some') # => warning: 'some' is mutable
Types::Strict::String.default('some'.freeze) # => no warning
Types::Strict::String.default('some', shared: true) # => no warning
```

**Comment by solnic** [comment]
That's a very good idea.
