### ISSUE TITLE
File type

### ISSUE THREAD

**Issue by kirs** [dry-rb/dry-types#28]
It would be great to have the built-in `File` type in `dry-data` and `dry-validation`.
Since `dry-validation` is a solution for request parameters / form validation, `File` a kind of must have type for forms.

@solnic what's your opinion?

**Comment by solnic** [comment]
@kirs yes, it'm open to add more types like `File`. I'm gonna hold off a little bit though, as I'm planning to refine behavior of `Type` objects for the next version. It should not take too long, shooting for early March, maybe earlier.

**Comment by kirs** [comment]
Does it mean that the public API will change?

**Comment by solnic** [comment]
@kirs no, it's gonna be an internal clean up with refined internals and an improved API for defining custom types. I need to make sure that more complex types like sums, optionals, default-values can work correctly without too much internal complexity. Although it's hard to say which API is public, the lib is not stable in general (< 1.0). Can you tell which APIs you depend on already?

**Comment by kirs** [comment]
I don't depend on any particular API, just wondering about your plans about it.

**Comment by jeremyf** [comment]
:+1: for this feature; I'd be up for working on the `File` type.

**Comment by solnic** [comment]
@jeremyf still up for the task? :)
