### ISSUE TITLE
Add Types.Contract

### ISSUE THREAD

**Issue by flash-gordon** [dry-rb/dry-types#324]
This will check if an object responds to specific methods. Checking arity is too hard to implement correctly in ruby so we'll only rely on the [new predicate](https://github.com/dry-rb/dry-logic/pull/56) in dry-logic.
Note: bump dry-logic version, bump dry-logic dep
Discussion with more info: https://discourse.dry-rb.org/t/support-for-type-classes/759

**Comment by waiting-for-dev** [comment]
@flash-gordon I submitted PR #323 with it
