### ISSUE TITLE
[Feature request] An extension that makes #try return a monad

### ISSUE THREAD

**Issue by jamiehodge** [dry-rb/dry-types#325]
It would be really nice if `Foo.try({..})` returned a `Dry::Monads::Try` or `Result`.

**Comment by flash-gordon** [comment]
@jamiehodge I moved it to dry-types, it should be done here. It's quite easy to implement in a way similar to dry-schema: https://github.com/dry-rb/dry-schema/blob/951488facaf6cc27b8a24887ef416e601b714671/lib/dry/schema/extensions.rb#L3-L5 Feel free to take a stab or this will wait another chance.
