### ISSUE TITLE
`omittable: true` is ignored when set by `transform_types`

### ISSUE THREAD

**Issue by renspr** [dry-rb/dry-types#326]
```ruby
#!/usr/bin/env ruby
gem     'dry-types', '=1.0.0'
gem     'dry-struct', '=1.0.0'
require 'dry-types'
require 'dry-struct'

module MyTypes
  include Dry.Types
end

class Foo < Dry::Struct
  transform_types do |type|
    type.meta(omittable: true)
  end

  attribute :attribute1, MyTypes::String
end

Foo.new
```

When I run the code above I get a `Dry::Types::MissingKeyError` on `:attribute1` but `transform_type` sets it to `omittable`.

Setting `attribute :attribute1, MyTypes::String.meta(omittable: true)` works.

**Comment by flash-gordon** [comment]
Please use `type.required(false)` instead. Setting omittable keys via meta should be done via the new API, however, it wasn't the goal to break the old one. I'll see if I can ship a patch with a warning so that people will know what exactly to update.

**Comment by renspr** [comment]
Hi,

thanks for the fast response. In my real app, I want to make every optional attribute omittable. Is this the "new API" you refer to?

```ruby
class MyStruct < Dry::Struct
  transform_types do |type|
    if type.optional?
      type.required(false)
    else
      type
    end
  end
end

class Foo < MyStruct
  attribute :attribute1, MyTypes::String
  attribute :attribute2, MyTypes::String.optional
end

Foo.new(attribute1: "Foo")
```

**Comment by flash-gordon** [comment]
Yes, this will work fine. Also, `.required(false)` == `.omittable`, choose what you like more.

**Comment by flash-gordon** [comment]
In 1.1.0 it'll be possible to load a patch restoring old behavior. This patch will later be removed so please migrate
```ruby
require 'dry/types/compat/omittable_meta'
```

**Comment by flash-gordon** [comment]
I changed my mind and replaced the patch with a warning.
