### ISSUE TITLE
[Feature Request] Type check for subclass

### ISSUE THREAD

**Issue by CodingAnarchy** [dry-rb/dry-types#337]
I'm working with a situation where I would like to do a type check that some value coming in is a class that inherits from `ActiveRecord::Base`, but `Types.Instance(ActiveRecord::Base)` fails the constraint saying that `Foo(...) violates constraint type?(ActiveRecord::Base, Foo(...)`.

It does not appear that an option exists to easily verify the incoming type is a class that has a parent class. (It appears the type check works if I have an instance of a class, but I have a class instance that I want to verify `klass.ancestors` includes `other_klass`.)

**Comment by flash-gordon** [comment]
I don't think we want to have such a check OOTB, it's not common to check classes with dry-types. If you're really sure you need it, this will work:
```ruby
Types::Instance(Class).constrained(lt: ActiveRecord::Base).
```

**Comment by CodingAnarchy** [comment]
I don't see how it would not be common.  `Types::Instance` is built in to the typing system to validate types that are not built-ins like integers, booleans, etc.  As Ruby is a rather dynamic language with native duck typing features, it is trivially common to find code written to handle inputs that inherit from a certain type, or include a certain module as a mixin.  Particularly in the context of larger applications like Rails.

I would urge you to reconsider the possibility of adding this in OOTB given that context.  Especially if it is as simple as a nicer way to implement the statement you provided.

**Comment by flash-gordon** [comment]
Just double-checking, you're talking about passing classes around, not instances? Like `type.(User)`, not `type.(User.new)` :)

**Comment by taryneast** [comment]
> I don't think we want to have such a check OOTB, it's not common to check classes with dry-types. If you're really sure you need it, this will work:
> 
> ```ruby
> Types::Instance(Class).constrained(lt: ActiveRecord::Base)
> ```

this doesn't work and I'mm not sure how it would.

I'll add our example use-case.
We want our users to enter addresses in lots of different places.
We have multiple sub-classes of an address for different purposes, from local-to-us (Australia) address, to global addresses, to address decorators, to addresses with extra validation-requirements.

One of our forms is used in multiple places and has an `address` attribute that should be able to accept all of these different kinds of addresses that all subclass off a global address class: `Address::Global`.

From the dry-types perspective it'd be very nice if we could have something like:

```
   attribute? :address, Dry::Types.InstanceSubclassOf(Address::Global)
```

Which could accept any one of:

```
  Address::Global
  Address::Au << Address::Global
  PostcodeValidatingAddressAuForm << Address::Au
```

**Comment by CodingAnarchy** [comment]
> Just double-checking, you're talking about passing classes around, not instances? Like `type.(User)`, not `type.(User.new)` :)

I missed this before, so my apologies, but the idea was to check that a specific object was an instance of an ActiveRecord model - we had a particular use case for a service class that applied specifically to such models with associated database tables.

**Comment by flash-gordon** [comment]
`Types.Instance` uses this predicate from dry-logic: https://github.com/dry-rb/dry-logic/blob/master/lib/dry/logic/predicates.rb#L15-L17 so I don't see how it fails to check if an object has a particular class in the ancestors' chain. If you have a reproducible example, please attach
```ruby
module Types
  include Dry::Types()
end

class A
end

class B < A
end

# [1] pry(main)> Types.Instance(A).(B.new)
# => #<B:0x00007faa48a59598>
```
