### ISSUE TITLE
Lost meta data

### ISSUE THREAD

**Issue by joelvh** [dry-rb/dry-types#339]
@flash-gordon from our chat on Zulip:

**Scenario 1:**

The meta data of an array member type is lost -- specifically, the `type: 'email'` disappears in this example:

```ruby
require(:name).maybe(
  Types::Strict::Array.of(Types::String.meta(type: 'email')).meta(param: true)
).member.type.meta
# => {}
```

**Scenario 2:**

Another scenario when `constrained` is added after `constructor`, for example:

```ruby
Types::Strict::String
  .meta(description: 'An email address')
  .constructor {
    # omitted
  }.constrained(format: /\A[^\s@]+@([\w\-]+\.)+(\w{2,})\z/i, max_size: 254)
  .meta
# => {}
```

This is resolved by switching the order:

```ruby
Types::Strict::String
  .meta(description: 'An email address')
  .constrained(format: /\A[^\s@]+@([\w\-]+\.)+(\w{2,})\z/i, max_size: 254)
  .constructor {
    # omitted
  }.meta
# => {:description=>"An email address"}
```

I have a feeling the `type: 'email'` issue in scenario 1 is potentially related to the constructor/constrained order.

**Comment by flash-gordon** [comment]
@joelvh something is missing in this snippet
```ruby
require(:name).maybe(
  Types::Strict::Array.of(Types::String.meta(type: 'email')).meta(param: true)
).member.type.meta
# => {}
```
Since this is not a reproducable example I'm not sure where's the problem. Could you add missing stuff so that I can be sure I fixed the issue?

**Comment by joelvh** [comment]
@flash-gordon I  think the original code was using a custom type that had the constructor/constrained methods on it. I didn't elaborate on that with my footnote in the description. Will try things out with the new release and let you know how it goes!

Thanks.
