### ISSUE TITLE
Add support ActiveSupport::HashWithIndifferentAccess for hash schema

### ISSUE THREAD

**Issue by Kukunin** [dry-rb/dry-types#354]
Hello. I use dry-types for my pure models and I'm happy. But I have troubles to get API params converted to my DRY structs. I use [Grape](https://github.com/ruby-grape/grape#params-class) for API, and by default it returns `ActiveSupport::HashWithIndifferentAccess` where keys are Strings rather Symbols. 

It's suitable for security, since client can send very long strings, and converting them to Symbols are not wishful.

The problem is that they don't work well with hash schemas:

```ruby
# OK
user_hash = Types::Hash.schema(name: Types::Strict::String)
user_hash[name: 'Josh'] # => {:name=>"John"}

# OK
user_hash['name' => 'John'] # => Dry::Types::MissingKeyError: :name is missing in Hash input

# NOT OK
hash = {'name' => 'John'}.with_indifferent_access
hash[:name] # => 'John'
user_hash[hash] # =>Dry::Types::MissingKeyError: :name is missing in Hash input
```

I know, that I can use `transform_keys(&:to_sym)`, but the original problem remains the same: if somebody will send a really huge string key in API payload, it will convert it to Symbol anyway despite there is no such key in the schema.

At least, can I write `transform_keys` to check if a given key inside the current schema and only then transform it to Symbol?

**Comment by solnic** [comment]
First of all, please don't ask support questions using issues. You can read our guidelines [here](https://github.com/dry-rb/dry-types/blob/master/CONTRIBUTING.md#issue-guidelines).

Regarding your problem, dry-types are not really designed to handle such cases. What you want is dry-schema which does exactly what you need.
