### ISSUE TITLE
Release dry-types 0.5.1 or 0.5.2

### ISSUE THREAD

**Issue by paneq** [dry-rb/dry-types#36]
The [installation instructions](https://github.com/dryrb/dry-types/tree/a7892c5f53d5f067822310e68b6150ba1dcadef7#installation) don't work right now because `dry-types` have never been released to rubygems. Only `dry-data` so far :)

Related: #21

**Comment by solnic** [comment]
inorite ;) it's gonna be released in early March (this year ;P)

**Comment by solnic** [comment]
https://rubygems.org/gems/dry-types :tada:
