### ISSUE TITLE
`.to_ast` crashes for nested attributes

### ISSUE THREAD

**Issue by tomgi** [dry-rb/dry-types#368]
**Describe the bug**

`.schema.to_ast` crashes for types that define nested attributes.

**To Reproduce**

Execute
```ruby
module Types
  include Dry.Types()
end

class Foo < Dry::Struct
  attribute :bar do
    attribute :baz, Types::String
  end
end

Foo.schema.to_ast
```

It crashes with
```
Traceback (most recent call last):
        9: from /usr/local/bin/irb:23:in `<main>'
        8: from /usr/local/bin/irb:23:in `load'
        7: from /usr/local/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        6: from (irb):13
        5: from /app/.bundle/gems/dry-types-1.2.0/lib/dry/types/constructor.rb:104:in `to_ast'
        4: from /app/.bundle/gems/dry-types-1.2.0/lib/dry/types/schema.rb:158:in `to_ast'
        3: from /app/.bundle/gems/dry-types-1.2.0/lib/dry/types/schema.rb:158:in `map'
        2: from /app/.bundle/gems/dry-types-1.2.0/lib/dry/types/schema.rb:158:in `block in to_ast'
        1: from /app/.bundle/gems/dry-types-1.2.0/lib/dry/types/schema/key.rb:113:in `to_ast'
NoMethodError (undefined method `to_ast' for Foo::Bar:Class)
Did you mean?  to_s
```

I think the problem is in https://github.com/dry-rb/dry-types/blob/784848d483e8b10c7aa6c39f77bb5703b565c23e/lib/dry/types/schema.rb#L158 I guess it should call `key.schema.to_ast` instead of `key.to_ast` for keys that represent nested attributes.

**Expected behavior**

Returns an ast instead of crashing :)

**Your environment**

- Affects my production application: **YES**
- Ruby version: 2.6.5
- OS: docker ruby:2.6.5-alpine

**Comment by flash-gordon** [comment]
`.to_ast` is not implemented in dry-struct, it's a missing feature for dry-struct, not a bug in dry-types

**Comment by tomgi** [comment]
Ok, the stack trace mentions only `dry-types` so I thought it belongs here.
I will report in `dry-struct` as a missing feature then.

Thanks
