### ISSUE TITLE
Types::Params::DateTime does not accept instance of DateTime as valid argument

### ISSUE THREAD

**Issue by dilcom** [dry-rb/dry-types#375]
**Describe the bug**

`Types::Params::DateTime[<instance of DateTime>]` raises exception. Same thing about other types that don't implement `#to_str` (Date, Time etc). Looks like it has been raised and fixed before https://github.com/dry-rb/dry-types/issues/131 but then reintroduced in https://github.com/dry-rb/dry-types/commit/8a29fefcc8a5f3f0d7aaa50478b4aba5f1e0b32a#diff-1a70a161fa018b2dc0b6dda5bc08069dR33-R35

**To Reproduce**

with dry-types (1.2.1)
```ruby
[1] pry(main)> Dry::Types::VERSION
=> "1.2.1"
[2] pry(main)> Types::Params::DateTime[DateTime.current]
Dry::Types::CoercionError: Mon, 09 Dec 2019 05:22:53 +0000 is not a string
from /somewhere/gems/dry-types-1.2.1/lib/dry/types/coercions.rb:66:in `to_date_time'
[3] pry(main)> Types::Params::DateTime[DateTime.current.to_s]
=> Mon, 09 Dec 2019 05:22:59 +0000
```

**Expected behavior**

`Types::Params::DateTime[<instance of DateTime>]` does not raise exception.

**Your environment**

- Affects my production application: **YES**
- Ruby version: ruby 2.6.1p33 (2019-01-30 revision 66950)
- OS: Ubuntu 18.04.3 LTS

**Comment by flash-gordon** [comment]
The tests added at that time made no sense, I changed them all to expect an exception, IIRC. I'm inclining to fix this but I want to point out that `Params::DateTime` expects a string, this is how it designed. It's made for accepting form data passed in the URL-encoded format, there's no room for other types but strings. If you pass `DateTime` objects in tests then you should serialize them to strings first. Are issues with testing your case here?

**Comment by dilcom** [comment]
Hm, that's true, I bumped into the issue while upgrading dry in our app and making tests pass so the problem is in test. However it may be an issue when using `Dry::Struct` with `attribute ..., Types::Params::DateTime` and initializing it either from form data or real DateTime (e.g. from ActiveRecord attributes). I guess in this case one should use `Types::Params::DateTime | Types::DateTime` but honestly I can't say it's obvious that passing `DateTime` to `Types::Params::DateTime` results in an exception. I'd expect it to just be accepted as is

**Comment by flash-gordon** [comment]
The problem is with this logic we'll need to add an extra check that is not needed in a typical production use case. So accepting `DateTime` has some performance penalty.

**Comment by dilcom** [comment]
This check can be added only in case when input does not respond to `#to_str` which otherwise would raise. So only these rare cases get the penalty.
What you say about use case for `Types::Params::DateTime` definitely makes sense but it was hard for me to grasp the logic without this additional explanation.
