### ISSUE TITLE
Default value can violate constraints

### ISSUE THREAD

**Issue by kwando** [dry-rb/dry-types#39]
I'm not sure if this is a bug or the intended behavior.

```ruby
type = Dry::Types["string"].constrained(min_size: 5).default("asd")
type.call(nil)  # => "asd"

type.call("asd")  # => Dry::Types::ConstraintError: "asd" violates constraint
```

**Comment by solnic** [comment]
Thanks for reporting this, I was aware of that and planning to improve this prior release. It's as a simple as asking the type if the value is valid before returning a default value instance.
