### ISSUE TITLE
JSON::Nil coerces empty strings to nil

### ISSUE THREAD

**Issue by flash-gordon** [dry-rb/dry-types#396]
**Describe the bug**

`Dry::Types['json.nil']` matches empty strings to `nil` which is frankly unexpected.

**To Reproduce**

```ruby
Dry::Types['json.nil'].('') 
=> nil
```

**Expected behavior**

```ruby
Dry::Types['json.nil'].('') 
=> ""
```

**Your environment**
 
- Affects my production application: **NOT SURE**
- Ruby version: all supported
- OS: n/a

**Comment by k0va1** [comment]
not actual anymore

fixed in https://github.com/dry-rb/dry-types/pull/397

**Comment by flash-gordon** [comment]
right
