### ISSUE TITLE
Possible compatibility issue between dry-struct and dry-monads

### ISSUE THREAD

**Issue by asoules** [dry-rb/dry-types#398]
**Describe the bug**

I'm running into an error that appears to be a compatibility issue between dry-struct and dry-monads that occurs when using `Do` notation with a subclass of `Dry::Struct`. 

`Dry::Monads::Do.for(methods)` calls `base.prepend` here: https://github.com/dry-rb/dry-monads/blob/v1.3.5/lib/dry/monads/do.rb#L93 which is aliased to `constructor` in dry-types here: https://github.com/dry-rb/dry-types/blob/v1.4.0/lib/dry/types/builder.rb#L133

The `constructor` method raises `undefined method 'with'`

**To Reproduce**

The following script demonstrates the error:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'dry-monads', '1.3.5'
  gem 'dry-struct', '1.0.0'
end

require 'dry/monads/do'

class MyStruct < Dry::Struct
  include Dry::Monads[:result]
  include Dry::Monads::Do.for(:call)

  def call
    yield foo
  end

  def foo
    Success(:foo)
  end

end

i = MyStruct.new
# 👆 should blow up here with: undefined method `with' for MyStruct:Class (NoMethodError)

puts i.call
```

on my machine, I see:

```
Traceback (most recent call last):
	4: from dry_types_undefined_with.rb:11:in `<main>'
	3: from dry_types_undefined_with.rb:13:in `<class:MyStruct>'
	2: from dry_types_undefined_with.rb:13:in `include'
	1: from /Users/asoules/.rvm/gems/ruby-2.5.1/gems/dry-monads-1.3.5/lib/dry/monads/do.rb:93:in `block (2 levels) in for'
/Users/asoules/.rvm/gems/ruby-2.5.1/gems/dry-types-1.4.0/lib/dry/types/builder.rb:130:in `constructor': undefined method `with' for MyStruct:Class (NoMethodError)
```

**Expected behavior**

The Struct should be initialized and `call` should return `:foo`

**Your environment**

- Affects my production application: **NO**
- Ruby version: tested with 2.4.4, 2.5.1, 2.6.1
- OS: Mac OS X

**Comment by asoules** [comment]
I just realized that 1.0.0 is not the latest version of dry-struct 🤦‍♂ updating to 1.3.0 resolves this error.

Perhaps Monads or Struct could require the newer version in it's gemspec?

**Comment by flash-gordon** [comment]
It has nothing to do with dry-monads, it's an incompatibility between new dry-types and old dry-struct. Unfortunately, there's no simple solution to this. We keep gem versions in dependencies relaxed because most changes are forward-compatible. Otherwise, we'd be in a versioning hell given the number of gems we maintain. Of course, newer versions of dry-struct depend on more recent dry-types, backward compatibility is less tricky.

**Comment by flash-gordon** [comment]
Yeah, forgot to mention, the right way is using latest versions :)
