### ISSUE TITLE
Dynamic default values

### ISSUE THREAD

**Issue by kwando** [dry-rb/dry-types#40]
Not sure if this is a bad idea or not, but here it is anyway.
```ruby
message_input = Dry::Types['hash'].schema(
  body:       'strict.string',
  from_id:    'strict.int',
  created_at: Dry::Types['strict.time'].default{ Time.now }
)

```

**Comment by solnic** [comment]
It is a good idea and a planned feature. I'll try to get this done prior the release, I may fail though :) If I do, then I'll add it in 0.6.1

**Comment by matanskii** [comment]
@solnic we found that doing something like
`attribute :timestamp, Types::Strict::Integer.default(DateTime.now.strftime("%Q").to_i)`
causes the value of the default timestamp on startup - rendering it static across different instances of the struct.
Are you aware of this behavior?

**Comment by solnic** [comment]
@matanskii I'm surprised this was a surprise, to be honest. Simply use a block-based syntax and it'll be evaluated every time a default is called.
