### ISSUE TITLE
Adding bottom type

### ISSUE THREAD

**Issue by qortex** [dry-rb/dry-types#400]
Add a bottom type that reject all types (opposite of `Any`). Called `never` in Typescript, which is pretty eloquent.

## Examples

Let's say I have an array of classes, and I want a variable to be an instance of any of these classes. With a `Never` type (name to be defined), it could be done like:
```ruby
any_of_those = my_types.reduce(Types::Never) do |memo, type|
  memo | Types.Instance(type)
end
```

Without the `Never` type, it's less elegant (need to single out first element as the `reduce` initializer, but then you need a special case if the array is empty).

I'm sure there are other use cases since it's a useful tool in type theory anyway.

(maybe there is a better way to do my example with existing capabilities?)

**Comment by flash-gordon** [comment]
I'm against adding it to the gem unless there's clear evidence it's useful. As for your example, it can be written as `my_types.reduce(:|)`. Please post it on [discourse](https://discourse.dry-rb.org) if you have other examples. Keep in mind, you can always construct such a type with something like `Types::Any.constrained(case: proc { false })`.

**Comment by qortex** [comment]
Waow nice, didn't realize the `reduce(:|)` trick.
Adding this behaviour for `nil` in the Sum types doc page could be useful.
