### ISSUE TITLE
Constructor is not applied properly to the result of types Sum

### ISSUE THREAD

**Issue by pyromaniac** [dry-rb/dry-types#408]
**Describe the bug**

It seems like constructor doesn't work properly over a Sum

**To Reproduce**

```ruby
(Types::Params::Nil | Types::Params::Integer).append { |v| v.nil? ? 42 : v }.call('')
=> nil
(Types::Params::Nil.append { |v| v.nil? ? 42 : v } | Types::Params::Integer).call('')
=> 42
```

**Expected behavior**

I actually expected in both cases for the value to fall back to 42. My idea is that the constructor is applied on top of the underlying operations accordingly to the precedence defined by parentheses.

**Your environment**

- Affects my production application: **Not yet**
- Ruby version: 2.6
- dry-types: 1.4.0

**Comment by flash-gordon** [comment]
It's not a bug. Your constructor block will run _first_. Then the block's result will be threaded through the type. You can see it here: https://github.com/dry-rb/dry-types/blob/da5ca5c70f63b6203f2bd1ad032307665cf03c2e/lib/dry/types/constructor.rb#L50-L53

**Comment by pyromaniac** [comment]
But then how to implement fallback to a value properly for any type? I'm referring #407

**Comment by flash-gordon** [comment]
I guess it would require a separate kind of type, very similar to https://github.com/dry-rb/dry-types/blob/da5ca5c70f63b6203f2bd1ad032307665cf03c2e/lib/dry/types/lax.rb

**Comment by pyromaniac** [comment]
@flash-gordon does it make sense to add a callback that can be run after the coercion? Something like `normalize` for the value? It will open a lot of flexibility.

**Comment by flash-gordon** [comment]
This works in master 🎉 
```ruby
[1] pry(main)> (Types::Params::Nil | Types::Params::Integer).append { |v, t| t.(v).nil? ? 42 : t.(v) }.call('')
=> 42
```
