### ISSUE TITLE
Optional & default type and nil input

### ISSUE THREAD

**Issue by flash-gordon** [dry-rb/dry-types#41]
#39 was closed but it seems that we can still have a value that violates type check/coercion rule.

```ruby
[4] pry(main)> Types::Maybe::Strict::Int.default(nil)[nil]
=> nil
```

I expected to receive an error on calling `default(nil)` or `None` as a result of the entire expression :)

On a large scale I want to have something like this:
```ruby
class MyOptionalValue < Dry::Types::Value
  constructor_type :schema
  attribute :foo, Types::Maybe::Strict::Int.default(nil)
end

v = MyOptionalValue.new({})
v.foo # => None
```
I store an empty hash value in DB but I want more strictness for my domain models. I put keys to the database only if they have values.

**Comment by solnic** [comment]
``` ruby
require 'dry-types'

module Types
  include Dry::Types.module
end

class MyOptionalValue < Dry::Types::Value
  constructor_type :schema
  attribute :foo, Types::Maybe::Strict::Int
end

puts MyOptionalValue.new({}).inspect
```

output:

```
#<MyOptionalValue foo=nil>
```
