### ISSUE TITLE
Types::Params::Integer incorrect coercion for numeric values

### ISSUE THREAD

**Issue by Somestuffman** [dry-rb/dry-types#416]
## Describe the bug

Calling Types::Params::Integer with numeric value returns integer, but expected to raise coercion error. This behavior also affects on dry-schema - i.e. calling params schema with float value expect to return error result instead of success.

## To Reproduce

```ruby
Types::Params::Integer.(Float(1.1)) # => Integer(1)
Types::Params::Integer.(Complex(1)) # => Integer(1)
Types::Params::Integer.(BigDecimal(1)) # => Integer(1)
Types::Params::Integer.(Rational(1)) # => Integer(1)
```

Dry-schema example:

```ruby
FooSchema = Dry::Schema.Params do
  required(:foo).filled(:integer)
end

FooSchema.(foo: 1.1) # => #<Dry::Schema::Result{:foo=>1} errors={}>
```

## Expected behavior

Calling Types::Params::Integer with numeric value should raise error.

```ruby
Types::Params::Integer.(Float(1.1)) # => SomeError
Types::Params::Integer.(Complex(1)) # => SomeError
Types::Params::Integer.(BigDecimal(1)) # => SomeError
Types::Params::Integer.(Rational(1)) # => SomeError
```

Dry-schema example:

```ruby
FooSchema = Dry::Schema.Params do
  required(:foo).filled(:integer)
end

FooSchema.(foo: 1.1) # => #<Dry::Schema::Result{:foo=>1.1} errors={:foo=>["must be an integer"]}>
```

## My environment

- Ruby version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
- OS: MacOS X
- dry-types v.1.4.0

## Possible solution

Add input numeric type validation to `to_int` method in Dry::Types::Coercions::Params:
```ruby
def self.to_int(input, &block)
  case input
  when Integer
    input
  when String
    Integer(input, 10)
  else
    raise TypeError
  end
rescue ArgumentError, TypeError => e
  CoercionError.handle(e, &block)
end
```

**Comment by flash-gordon** [comment]
It is expected. Generally speaking, `Params::Integer` should only accept strings. We made it work with other inputs to make it more convenient in tests where you can use numbers, not strings. So it behaves according to our "specification". It's true we could reject floats and other numbers but I think it's not worth the effort. You can build your own type with strict rules.

**Comment by solnic** [comment]
What Nikita wrote, plus notice that you can do this:

```ruby
irb(main):010:1* schema = Dry::Schema.Params do
irb(main):011:1*   required(:foo).filter(format?: /\d+/).value(:integer)
irb(main):012:0> end
=> #<Dry::Schema::Params keys=["foo"] rules={:foo=>"key?(:foo) AND key[foo](int?)"}>
irb(main):013:0* schema.(foo: "1.1").errors
=> #<Dry::Schema::MessageSet messages=[#<Dry::Schema::Message text="must be an integer" path=[:foo] predicate=:int? input="1.1">] options={:failures=>true}>
irb(main):014:0> schema.(foo: "1").errors
=> #<Dry::Schema::MessageSet messages=[] options={}>
```

**Comment by Somestuffman** [comment]
Thanks for the fast replies!
Misunderstand why Params::Integer?  In my opinion, Params::Integer can accept any type, but coerce (do not raise error) only integers and stings. For all other types it should raise exception (edited the Possible solution). Converting all numeric values to integer looks like side effect. As an example Rails permitted params - they already have basic coercion, and passing float param to params schema with integer just truncate this float and return integer (same thing with dry-struct).
One more thing I mentioned is when passing string with i.e. float number raises error (just like in Piotr example :)).

**Comment by flash-gordon** [comment]
Because `Params` is about handling URL parameters. Query string parsers return strings or hashes AFAIK, at least in Ruby.

**Comment by Somestuffman** [comment]
Yes, your are right. Looks like specific rails case, following your recommendations I'll add custom strict type. Thanks a lot for your help!

**Comment by solnic** [comment]
To be honest, I don't remember why exactly it was done like that but in general, our approach with dry-types and coercions *is to be strict*; however, I suspect in this case pragmatism won because it'd be a serious divergence from what people are used to, as this is how it works in ActiveModel/ActiveRecord...unless I'm mistaken?

**Comment by flash-gordon** [comment]
Oh, I remember, it was a requirement from Hanami when it got upgraded from its internal validation lib to dry-validation.
Plus there was a case where middleware modified params injecting coerced integers. It's funny how selective my memory is :)

**Comment by Somestuffman** [comment]
I faced this issue in Rails and dry-validation. Rails mixing query_parameters (not coerced) and request_parameters (coerced by selected Content-Type, in my case it is json), so passing float params from controller to contract with integers fields behaves unexpected for me (expecting schema validation will fail). All in all, defining type with custom constructor solves this issue:
```ruby
CoercibleInteger = Types::Integer.constructor do |value|
  case value
  when String
    Integer(value, 10)
  else
    value
  end
end
```

**Comment by solnic** [comment]
@Somestuffman OK sounds good, let's leave it at that but I'd like to revisit this when planning 2.0.0, so stay tuned
