### ISSUE TITLE
Anonymous Dry::Types based module cannot be extended

### ISSUE THREAD

**Issue by chriscz** [dry-rb/dry-types#421]
## Describe the bug
I unable to extend my custom types module `T1` . In a current project I want to do this this for ease of access to type the type constants. It would be useful if dry-types modules acted as would a normal ruby module, supporting extension.

## To Reproduce

The following, courtesy of @solnic  raises an error when pasted into a console 

**(1) Anonymous modules case**
```
T1 = Module.new { include Dry.Types(); ID = Integer }
T2 = Module.new { include T1 }
T2::ID
# => NameError: uninitialized constant T2::ID
```

However the following seems to work correctly:
**(2) Named modules case**
```
module T1
  include Dry::Types()
  ID = Integer
end

module T2
  include T1
end

T2::ID
# => <Dry::Types[Constrained<Nominal<Integer> rule=[type?(Integer)]>]>
```
So the second case actually address my original issue (I was using `extend` instead of `include`)

## Expected behavior
I expected `ID` to be accessible through `T2` in case 1.

**Comment by flash-gordon** [comment]
It has nothing to do with dry-types, it's how lexical scoping works in ruby.
This code
```
T1 = Module.new { include Dry.Types(); ID = Integer }
```
defines a global constant `ID`, not a constant in `T1`.
This is why rspec has workarounds: https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/LeakyConstantDeclaration
We could have something similar in dry-types but that would be ugly and beyond the scope of the gem IMO.

**Comment by solnic** [comment]
Oh my oh my, this is my bad. Right, so it looks like we're good @chriscz ? 🙂

**Comment by flash-gordon** [comment]
Np, I just wasn't around when it was discussed on zulip. But it's good to have this issue as a reference anyway, this corner of ruby is 💯 counterintuitive.

**Comment by chriscz** [comment]
@solnic yes we're good :). @flash-gordon that's super interesting, I'll definitely be doing more reading into Ruby semantics since I'm quite interested in Ruby's meta-programming capabilities . Thanks guys!
