### ISSUE TITLE
https://dry-rb.org/gems/dry-types/ not at latest version

### ISSUE THREAD

**Issue by Samsinite** [dry-rb/dry-types#426]
## Describe the bug

When viewing the documentation at https://dry-rb.org/gems/dry-types/, it only shows version 1.2 and below.

## To Reproduce

- Navigate to the documentation at https://dry-rb.org/gems/dry-types/
- Look at the version select

## Expected behavior

- Would expect to see versions 1.3 - 1.5.1

**Comment by krainboltgreene** [comment]
This doesn't seem to be the case anymore.
