### ISSUE TITLE
Decimal doesn't convert Floats

### ISSUE THREAD

**Issue by joevandyk** [dry-rb/dry-types#44]
```
class Sku < Dry::Types::Struct
  attribute :price, Types::Coercible::Decimal
end
p Sku.new(price: 1.2).price
# dry-types-0.6.0/lib/dry/types/constructor.rb:30:in `BigDecimal': can't omit precision for a Float. (ArgumentError)
```

I think ideally dry-types would convert floats to a string before doing `BigDecimal.new(input)`

**Comment by solnic** [comment]
This uses `Kernel.BigDecimal` method so it's gonna work like that. What's your use case? What's the data source?

**Comment by solnic** [comment]
I'm gonna close this one in favor of #46

**Comment by joevandyk** [comment]
```
class Sku < Dry::Types::Struct
  attribute :price, Types::Strict::Decimal
end

json = '{"price": 1.99}'
Sku.new(JSON.parse(json).symbolize_keys)
```
for example would be something i'm likely to do (possibly using a better way to symbolize keys)

**Comment by solnic** [comment]
@joevandyk in this case I would use hash schemas with proper coercions, for now just use `Form::*` but we need `JSON::*` too (which is a planned feature). If the json is not a trusted resource, I suggest using dry-validation with coercion. Key-symbolization can be done with `Types::Hash#symbolized`.
