### ISSUE TITLE
Types::Coeercible::Integer, should this use Base 10?

### ISSUE THREAD

**Issue by radar** [dry-rb/dry-types#440]
## Describe the bug

```
Types = Dry.Types()
int = Types::Coercible::Integer
int.(2) #=> 2
int.("2") #=> 2
int.("100") #=> 100
int.("0100") #=> 64
```

I think this is because Types::Coercible::Integer is using the default Ruby coercion of wrapping in `Integer`. However, this interprets things like hex digits and `0b100` binary notation.

## Expected behavior

The `Coercible::Integer` type to use Base 10, by way of `Integer(value, 10)`.

```
int.("0100") #=> 100
```

I know I can get this by doing this instead:

```
Int = Constructor(Integer, &:to_i)
```

**Comment by flash-gordon** [comment]
See https://github.com/dry-rb/dry-types/issues/255

**Comment by flash-gordon** [comment]
FWIW, `Int = Constructor(Integer, &:to_i)` is a poor substitution. For instance, `.to_i` will coerce any invalid string to 0 which makes no sense in my opinion. Also, cases like `"123foo"` -> 123 and so on.
