### ISSUE TITLE
Rails hot reloading in development environment causes error in Dry::Container::Error

### ISSUE THREAD

**Issue by insalab** [dry-rb/dry-types#45]
I have class in my project
```
class PhoneToken::Generate < Dry::Types::Struct
  ...
end
```
It works fine until I edit file containing this code and do a request. Rails tries to reload edited file which leads to this error:
```
Dry::Container::Error - There is already an item registered with the key "phone_token.generate"
```
The same behavior can be reproduced using `reload!` in rails console.

**Comment by solnic** [comment]
There's [dry-data-rails](https://github.com/jeromegn/dry-data-rails) made for dry-data, so it's a matter of renaming things there and pushing a new release. Please report an issue there. I'm gonna close this one as dry-types will never have any rails-specific code, so it's an external concern.

**Comment by szyablitsky** [comment]
@solnic thank you for the link! I did not know that solution already exist.

**Comment by jeromegn** [comment]
I renamed things and renamed the gem to dry-types-rails (version 0.2.0).

**Comment by solnic** [comment]
@jeromegn great, thanks for the info!
