### ISSUE TITLE
Undefined method after upgrading dependencies.

### ISSUE THREAD

**Issue by coding-bunny** [dry-rb/dry-types#451]
## Describe the bug

Upgraded `dry-core` and `dry-logic` during some maintenance, `dry-types` remained the same, but suddenly the entire framework stopped working because of the following error:

```
Failure/Error: require 'dry-types'

NoMethodError:
  undefined method `build' for Dry::Logic::Rule::Predicate:Class

            Logic::Rule::Predicate.build(
                                  ^^^^^^
```

## To Reproduce

* Use `dry-types ~> 1.5`
* Upgrade `dry-core` from 0.8 -> 0.9
* Upgrade `dry-logic` from `1.2.0` to `1.3.0` 

## Expected behavior

Expect that `dry-types` still works as expected.
The fix was to manually require `dry-logic` before `dry-types`

## My environment

- Affects my production application: **NO**
- Ruby version: 3.1.2
- OS: OS Ventura

**Comment by flash-gordon** [comment]
You'll need to upgrade dry-core to 1.0+.

**Comment by coding-bunny** [comment]
> You'll need to upgrade dry-core to 1.0+.

neither `dry-types` or `dry-struct` has that as a requirement, which are the two gems I am using.
If they pull in `dry-logic` and `dry-core`, shouldn't they set the requirement then to `>= 1.0` instead of `~> 0.9, >= 0.9` ?

**Comment by flash-gordon** [comment]
It's not possible to change old releases to set an upper bound on dry-logic. It's unfortunate, but the alternative would be to bump all gems to 2.0 which. Regarding the problem itself, gems were switched to using zeitwerk, now there's no need to require specific files or gems. If you depend on dry-types, `require 'dry-types'` will suffice. Given you upgraded all gems to the latest versions.

**Comment by flash-gordon** [comment]
TBH maybe just upgrading dry-type to the latest compatible will do. It's just hitting 1.0 in dry-core was a major disturbance, now things look settled.

**Comment by coding-bunny** [comment]
upgraded `dry-types` to `~> 1.7` and `dry-struct` to `~> 1.7` and that seems to resolve it properly.
