### ISSUE TITLE
Rename `Coercible::*` to `Kernel::*` for clarity

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-types#46]
I believe the `Coercible` types may cause confusion as people may expect complex coercion logic under this category whereas it only provides `Kernel` type constructor methods (like `Kernel.Integer` etc.).

**Comment by mrbongiolo** [comment]
It makes sense. Later on you can actually use the `Coercible` namespace for more complex coercions, if needed or if someone just wants to extend Dry::Types.

**Comment by daniels** [comment]
As one who didn't realize that the coercions in this namespace were only expected to utilize the `Kernel` methods I'm still note entirely sure about the name change. It says more about the implementation but less about what's special about these types. I think I get more information from `Types::Coercible::String` than from `Types::Kernel::String`.

**Comment by joevandyk** [comment]
What's the reasoning for only doing Kernel coercions? Simplicity?

**Comment by solnic** [comment]
@joevandyk intentional usage. ie kernel coercions can be useful in low-level library code.

`Coercible::*` is not going to be very common but there are use cases for it. I'm planning to add more categories, like `JSON::*` (which will probably share a lot with `Form::*`) and probably more once we discover new use cases.

What I want to avoid is "generic coercions" that we have in libs like virtus and its clones. This approach has failed and I don't want to repeat the same mistake.

Please also see my [comment](https://github.com/dry-rb/dry-types/issues/44#issuecomment-201214855) in the related #44
