### ISSUE TITLE
Dry-Types Gem Issue with Coercing Float Strings to Integers

### ISSUE THREAD

**Issue by gottfrois** [dry-rb/dry-types#472]
## Describe the bug

The Dry-Types gem exhibits unexpected behavior when attempting to coerce string representations of floating-point numbers into integers. While it successfully coerces a string representing an integer (e.g., `"123"`) to an integer (`123`), it fails to coerce a string that represents a floating-point number (e.g., `"123.0"`) into an integer, instead raising a `Dry::Types::CoercionError`.

## To Reproduce

1. Ensure you have the `dry-types` gem installed and required in your Ruby environment.
2. Open an IRB session or include the following code in a Ruby script.

```ruby
require 'dry-types'

module Types
  include Dry.Types()
end

# Example of expected behavior:
puts Types::Coercible::Integer['123']
# Output: 123

# Example of the issue:
puts Types::Coercible::Integer['123.0']
# Expected Output: 123
# Actual Output: Dry::Types::CoercionError: invalid value for Integer(): "123.0"

puts Types::Params::Integer['123.0']
# Expected Output: 123
# Actual Output: Dry::Types::CoercionError: invalid value for Integer(): "123.0"
```

## Expected behavior

When passing a string representing a floating-point number to `Types::Coercible::Integer`, the gem should successfully coerce it to an integer by removing the decimal part, if it does not affect the integer value, e.g., `"123.0"` should be coerced to `123`. This is consistent with the expected behavior when coercing a string representing a whole number without a decimal point.

## My environment

- Affects my production application: **YES**
- Ruby version: `ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin22]`
- OS: `macOS 13.4 Ventura (22F66)`

**Comment by flash-gordon** [comment]
It is expected because per [docs](https://dry-rb.org/gems/dry-types/1.7/built-in-types/):
> Coercible types will attempt to cast values to the correct class using kernel coercion methods

As soon as `Integer("123.0", 10)` starts returning `123` instead of raising an error `Coercible::Integer` will follow :)
