### ISSUE TITLE
Freeze attributes belonging to Dry::Types::Value objects?

### ISSUE THREAD

**Issue by backus** [dry-rb/dry-types#65]
Initializing a struct or value object with an existing instance just returns that object:

```ruby
require 'dry/types'

class Name < Dry::Types::Value
  attribute :first, 'strict.string'
  attribute :last,  'strict.string'
end

name1 = Name.new(first: 'john', last: 'doe') # => #<Name first="john" last="doe">
name2 = Name.new(name1)                      # => #<Name first="john" last="doe">

name1.equal?(name2) # => true

name1.first.reverse!

name1.first # => "nhoj"
name2.first # => "nhoj"
```

I would say that `dry-types` should *at least* freeze each attribute's value. I realize that a `Dry::Types::Value` instance itself is frozen but its members should probably also be frozen.

**Comment by backus** [comment]
I might add a separate issue for this, but I think that `Dry::Types::Struct` objects should also change their behavior such that attribute values are duplicated upon instantiation:

```ruby
require 'dry/types'

class Name < Dry::Types::Struct
  attribute :first, 'strict.string'
  attribute :last,  'strict.string'
end

name1 = Name.new(first: 'john', last: 'doe') # => #<Name first="john" last="doe">
name2 = Name.new(name1)                      # => #<Name first="john" last="doe">

name1.equal?(name2) # => false

name1.first.reverse!

name1.first # => "nhoj"
name2.first # => "john"
```

this way you can still have mutable structs if you want but you still aren't as likely to accidentally mutate the state of another object.

**Comment by solnic** [comment]
> I might add a separate issue for this, but I think that Dry::Types::Struct objects should also change their behavior such that attribute values are duplicated upon instantiation

We can provide a special struct type that does that if it could be useful. But I wouldn't want this to be THE behavior of every struct, because of performance cost.

**Comment by solnic** [comment]
True, we should deeply freeze its members. It's gonna cost a lot in terms of performance though so it should be properly documented.

**Comment by timriley** [comment]
Given the performance cost, can you imagine anyone actually wanting to use such a class?

**Comment by solnic** [comment]
Of course, there are places where being so paranoid is a good idea, esp when you rely heavily on object's equality and you need to make sure nothing can mutate them. I had this kind of code a couple of times, I always used truly immutable objects there.

**Comment by backus** [comment]
> It's gonna cost a lot in terms of performance though so it should be properly documented.

Assuming this is properly documented are you comfortable then with moving forward on this? I'm happy to do a PR at some point I just want to make sure that this is inline with what the project's goals

**Comment by solnic** [comment]
Yes let's do this

**Comment by solnic** [comment]
bump :)

**Comment by backus** [comment]
On it. I assume you are fine with pulling in IceNine as a dependency for this?
