### ISSUE TITLE
Types::Bool.default(false) does not work

### ISSUE THREAD

**Issue by edward6882990** [dry-rb/dry-types#73]
For attempting to set a default value `false` to Types::Bool, I am getting constraint violation because of the following line of code:

https://github.com/dry-rb/dry-types/blob/master/lib/dry/types/builder.rb#L26

because `false` in there was ignored and block wasn't given. Is this something expected? Or is Bool by default has a default value of false?

So far I worked around it by doing `Types::Bool.default { false }`, but having to create a proc does drag the performance down a little bit.

**Comment by solnic** [comment]
Ugh that is a silly bug. I'll fix it

**Comment by edward6882990** [comment]
Thanks!
