### ISSUE TITLE
Add form coercion for array types when they are blank

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-types#76]
This relates to https://github.com/dry-rb/dry-validation/issues/102, in which I outlined that there's no simple way to include empty arrays in HTML form submissions. We've been exploring thus further with our [formalist](http://github.com/icelab/formalist)-generated forms, and have come to this arrangement:

When a form is expected to submit an array as one of its fields, but that array is empty, then instead replace it with something like this:

```html
<input type="hidden" name="category_ids">
```

This means that we now get params like this being included in our form submission for an array-type field with nothing included:

```ruby
{"category_ids" => ""}
```

Now, if we had a schema like this:

```ruby
schema = Dry::Validation.Form do
  key(:category_ids).each(:int?)
end
```

When we run it with that input, right now we get an error, because there's no specific form coercion rules for arrays:

```ruby
schema.("category_ids" => "").messages
# => {:category_ids=>["must be an array"]}
```

Since the empty string is an HTML form's standard "empty value", I'd like to propose that we add a form coercion for this when we expect the field to be an array. In this case, I'd propose that we actually coerce it to `nil`, like we do for other HTML type coercions here, like `int`:

```ruby
def self.to_int(input)
  return if empty_str?(input)

  # ... rest of coercion logic ...
end
```

By coercing to `nil`, then we can have the flexibility to use a type in our validation schema with a default value (like an empty array), which is what you suggested in https://github.com/dry-rb/dry-validation/issues/102, @solnic.

Would you be happy to have this coercion added to dry-types? I'll go ahead and build it if so.

Thanks!

**Comment by solnic** [comment]
Yeah I think it's safe to assume that coercing empty string to an empty array makes perfect sense in `Form`.

**Comment by timriley** [comment]
@solnic Great, thanks! A PR will be forthcoming.
