### ISSUE TITLE
Replace kleisli with dry-monads

### ISSUE THREAD

**Issue by flash-gordon** [dry-rb/dry-types#80]
It looks like we have some issues with kleisli gem. First of all the author didn't release the new gem version that would include much welcome removal of obsolete blank_slate hack. When I tried to add dry-types to my existing rails project this first thing I saw was StackOverflowError. It if very unfriendly error tbh :) After some time of debugging I figured out that the problem was caused by [other gem](https://github.com/kschiess/parslet/pull/154) that uses blankslate (without reason, actually). I absolutely don't blame the author at all, it is OSS so he can do whatever he wants. 

The second issue is that kleisli adds some pollution to the global environment. E.g. it adds `#Maybe` and `#Right` methods to object so the become a private members of almost any object in runtime. I think it is against our rules :) Also I Maybe/Either methods a lot and found a tricky problem with using them inside a namespaced blocks of dry-container because [NamespaceDSL](https://github.com/dry-rb/dry-container/blob/master/lib/dry/container/namespace_dsl.rb) uses SimpleDelegator that inherits from BasicObject and _does not_ delegate to private methods so I got really unexpected NoMethodError.

Third is that I think we do not need most of kleisli classes. I doubt we need more than Maybe + Either. And from the other side we can add some other stuff to a potential monad/fp dependency.

Finally I think the API of kleisli is quite good but not perfect. Twisting it a bit would be really nice.

I propose to create a minor dry-monad/dry-fp dependency so we can solve all that issues. I quickly made a couple of files (untested :)) that can become a new gem:
Maybe: https://gist.github.com/flash-gordon/a6e6c0956b802d387e2fe81d9b7530b7
Either: https://gist.github.com/flash-gordon/446d38a1c7295e1b9ffcbe1302741522

Any thoughts?

**Comment by solnic** [comment]
Yes I wanted to propose this too. So big thumbs up

**Comment by AMHOL** [comment]
@solnic you're supposed to be on holiday, are you drunk yet?

**Comment by timriley** [comment]
This sounds good to me. I think an "Either"/"Result" and a "Maybe" monad and an overall structure that adheres to our non-intrusive approach would be a great start (and should cover most of our current use cases).

**Comment by timriley** [comment]
@flash-gordon I've just created https://github.com/dry-rb/dry-monads (used a pluralised name to match e.g. dry-types) and added you to the contributors group, which'll give you write access. Looking forward to seeing you put something together! I'll file further thoughts as issues over on that repo :)

**Comment by flash-gordon** [comment]
@timriley got it! Stay tuned :)

**Comment by AMHOL** [comment]
I think the singular form would be better, it makes sense for dry-types and dry-validations as you can't describe the objects that you create with them as "a types" or "a validation" where as "a monad" works perfectly, mind if I change the repo name @timriley @flash-gordon ?

**Comment by flash-gordon** [comment]
Personally I don't mind

**Comment by timriley** [comment]
My other thing for the plural form as the name was because this gem would be a collection of monads – we're already using 2 (Either and Maybe) and it's no unlikely that others may come later.

However, I'd be just as happy with `Dry::Monad::Either` as I would be with `Dry::Monads::Either`, so I'd be happy for you to rename, @AMHOL :)

**Comment by AMHOL** [comment]
Ahh OK, that makes sense, you've convinced me otherwise now so dry-monads works for me lol

**Comment by solnic** [comment]
@flash-gordon can you push your ideas to a branch under dry-monads project and open a PR to discuss APIs?

**Comment by flash-gordon** [comment]
@solnic done. Here it is: https://github.com/dry-rb/dry-monads/pull/1 let's discuss it.
