### ISSUE TITLE
Sum types with structs are not supported

### ISSUE THREAD

**Issue by davidpelaez** [dry-rb/dry-types#81]
I realized I cannot use `|` to create sum types with `Dry::Types::Struct`. The following doesn't work with the latest version from Rubygems:

```ruby
class DiscreetFilter < Dry::Types::Struct 
     attribute :target_column, Types::Strict::String
     attribute :name, Types::Strict::String
     attribute :type, Types::Strict::String.enum("DISCREET")
     attribute :id, Types::Strict::String
     attribute :active, Types::Bool
     attribute :values, Types::Array.member(Types::DiscreetFilterValues)
  end

  class RangeFilter < Dry::Types::Struct 

    RangeFilterValue = Types::Hash.schema({
      range_max: Types::Coercible::Float,
      range_min: Types::Coercible::Float
    })

    attribute :target_column, Types::Strict::String
    attribute :name, Types::Strict::String
    attribute :type, Types::Strict::String.enum("RANGE")
    attribute :unit, Types::Strict::String
    attribute :id, Types::Strict::String
    attribute :active, Types::Bool
    attribute :values, Types::Array.member(RangeFilterValue)
  end

  #throws: NoMethodError: undefined method `|' for Types::DiscreetFilter:Class
  LineFilter = Types::DiscreetFilter | Types::RangeFilter 

```

Is there a reason why this shouldn't be added? It seems to me sum types should be supported here to, right?

I also tried naively to do `Dry::Types::Sum.new Types::DiscreetFilter, Types::RangeFilter` but that doesn't work because there's a `try` method missing.

**Comment by flash-gordon** [comment]
You should use Type objects for your Struct classes, not Struct classes themselves. Try this: `LineFilter = Dry::Types[DiscreetFilter] | Dry::Types[RangeFilter] `.

**Comment by solnic** [comment]
We should probably consider adding `Struct.|` interface as I suspect many people will be confused by this. ie you can do `attribute :user, User` so this kind of implies that `|` should work with struct/value classes.
