### ISSUE TITLE
(Types::Form::Date | Types::Strict::Nil) not working for nil?

### ISSUE THREAD

**Issue by timhabermaas** [dry-rb/dry-types#83]
Using gem version `0.7.1`.

I might be misunderstanding `|`, but I expected it to work as a fallback if the left coercion fails.

Code
---

```ruby
(Types::Form::Date | Types::Strict::Nil)[nil]
```

Result I get
---

```
Dry::Types::ConstraintError: nil violates constraints (#<struct Dry::Types::Result::Failure input=nil, error="no implicit conversion of nil into String">)
	from dry-types-0.7.1/lib/dry/types/sum.rb:31:in `block in call'
	from dry-types-0.7.1/lib/dry/types/sum.rb:44:in `try'
	from dry-types-0.7.1/lib/dry/types/sum.rb:30:in `call'
```

Result I expected
---

```ruby
nil
```

`(Types::Form::Decimal | Types::Strict::Nil)[nil]` works btw, so it seems to be specific to the `Form::Date` type.

**Comment by timhabermaas** [comment]
Turns out `Types::Form::Date` raises a `TypeError` when given `nil`. I could fix this by handling `nil`/`TypeError` in `Types::Coercions#to_date`, but I'm not sure passing in `nil` to a `Form` type is even intended. None of the specs seem to test for it. `Types::Form::Decimal[nil] # => nil` works just fine, though.

Since `Form::Date` seems to be the only coercible `Date` type I don't see another way to express "it's either a string containing a date format or nil", though.

**Comment by solnic** [comment]
Try this `Strict::Nil | Form::Date`

**Comment by timhabermaas** [comment]
Thanks for clearing this up, @solnic! I'm gonna close this issue since using `Strict::Nil | Form::Date` does indeed fix my problem.
