### ISSUE TITLE
`Coercions::Form.to_int` should not blindly call `to_i` on input

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-types#86]
Currently we do this [here](https://github.com/dry-rb/dry-types/blob/master/lib/dry/types/coercions/form.rb#L25). This is a big mistake since ruby coercion logic in `to_i` is weird ie: 

```
irb(main):001:0> "12fafsa".to_i
=> 12
```

Would be great to fix it using an approach that won't be too slow. Probably applying a regex is the only solution here though.

Refs dry-rb/dry-validation#132
Refs dry-rb/dry-validation#135

**Comment by flash-gordon** [comment]
@solnic how about `Kernel#Integer`? 
```ruby
$ irb
2.3.1 :001 > Integer('123')
 => 123
2.3.1 :002 > Integer('123asd')
ArgumentError: invalid value for Integer(): "123asd"
	from (irb):2:in `Integer'
	from (irb):2
	from /Users/gordon/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
2.3.1 :003 > Integer('')
ArgumentError: invalid value for Integer(): ""
	from (irb):3:in `Integer'
	from (irb):3
	from /Users/gordon/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
2.3.1 :004 >
```
I can send a PR of course ;)

**Comment by solnic** [comment]
Oh of course, this should be faster than a regexp. I know because we already checked rescuing from an error vs regex matching, see [here](https://github.com/dry-rb/dry-logic/pull/6). Feel free to just fix it (with proper test cov of course) and just push to master directly.

**Comment by flash-gordon** [comment]
Sure, will do.
