### ISSUE TITLE
Code smell? Custom constructor for Strict type can need type-check

### ISSUE THREAD

**Issue by greghuc** [dry-rb/dry-types#93]
Hi there,

As a first-time user of dry-types, I'm reporting a 'code smell' that confused me when I ran into it.

I created a TrimmedString type using Strict::String and a custom constructor which trims the supplied input:  ```TrimmedString = Strict::String.constructor { |value| value.strip }```

What I expected:
* ```TrimmedString[' Trim me ']```, the supplied String value is trimmed and returned
* ```TrimmedString[3]```, a 'Dry::Types::ConstraintError" is thrown since input is not a String

For ```TrimmedString[3]```, this is not what happened. Instead, the code threw an exception because the strip method was not found on the Fixnum 3. This is the code smell: I didn't expect the custom constructor to be called, since the input is not a String (and I specified Strict::String). The fix is easy enough: ```TrimmedString = Strict::String.constructor { |value| value.kind_of?(::String) ? value.strip : value }```

I realise that I will get things wrong since I'm a new user of dry-types, and am piecing things together from blog posts etc (the docs for dry-types latest are not complete). However, this is something that didn't feel intuitively right, and may trip up others.

Thanks for a nifty library!

### Example program
````
require 'bundler/setup'

require 'dry-types'

module Types
  include Dry::Types.module

  TrimmedString = Strict::String.constructor { |value|
    # Throws exception: undefined method `strip', when supplied Fixnum
    value.strip
    # Replace with type-checked line below to stop exception
    # value.kind_of?(::String) ? value.strip : value
  }

end

puts Types::TrimmedString[' Trim me ']
puts Types::TrimmedString[2]

# Output
Trim me
app/types/wtf.rb:10:in `block in <module:Types>': undefined method `strip' for 2:Fixnum (NoMethodError)
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/dry-types-ed7a7f605dfa/lib/dry/types/constructor.rb:28:in `[]'
	from /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/dry-types-ed7a7f605dfa/lib/dry/types/constructor.rb:28:in `call'
	from app/types/wtf.rb:18:in `<main>'
```

**Comment by solnic** [comment]
This will be improved in 0.8.0. Thanks for reporting

**Comment by solnic** [comment]
I'm not sure if I want to make it work the way you expected it to work. The role of a constructor is to produce a valid input for its type. It would be weird to apply a constructor after applying type checks. I need to think about this a bit more.

**Comment by greghuc** [comment]
I’ve also changed my mind on this, for the same reason. Am happy for this issue to be closed.

**Comment by solnic** [comment]
Let's keep it open. I have feedback from other people that they expected this behavior too, and I can see how this might not feel intuitive so I'd like to address this somehow /cc @mrbongiolo

**Comment by huyderman** [comment]
It might be just because I'm now used to this behavior, but it seems reasonable that `#constraint` (and per extension "strict" types) validates the result. This is needed for constructors which coerce a value since the input would not normally be of the same type. Many coercers/parsers also return `nil` when unable to parse the input. E.g. `Dry::Types['strict.time'].constructor(Chronic.method(&:parse))`.

To validate input instead of output, doing something like `Strict::String.constructor { |value| Strict::String[value].trim }` feels more "right" to me, although it might be useful with a shorthand.
