### ISSUE TITLE
AST compiling failling with an array without member rules

### ISSUE THREAD

**Issue by mrbongiolo** [dry-rb/dry-types#95]
Falling AST:
```ruby
ast = [
      :type, [
        "hash", [
          :schema, [
            [:key, [:skills, [:type, "array"]]]
          ]
        ]
      ]
    ]
```

This fails because `visit_array` tries to define a member rule every time, even when they don't exist.

I did some small tests and this seemed to solve the issue:
```
def visit_array(node)
  if node
    registry['array'].member(call(node))
  else
    registry['array']
  end
end
```
But I'm not sure if this would impact other usages of the AST with an array.

This is basically needed for schema validations that are done like that: `required(:skills).filled(:array?)`, in which we just want to ensure that the key has an array, but the values inside of it doesn't matter.

Related: https://github.com/dry-rb/dry-validation/issues/170

**Comment by solnic** [comment]
We should handle this use case, but I gotta ask - why the array elements "don't matter"? What I'm trying to do with these libs is to make people concious about type safety in a rather strict way. If you're using these libs to handle input from "the outside world" then you should be conservative about type expectations. I also understand that these libs might be used in contexts where less strict approach is fine, so I'm wondering what's your use case now :)

**Comment by mrbongiolo** [comment]
I was thinking about that too, I think that we will always care about the contents of an array in some way. My real use case was that `each` itself wasn't checking before hand if something was an array and blew up when calling `map`, that's why I wanted to set the `:array?` rule there, but it then throw that error.

Maybe we should raise a more meaningful exception when someone is trying to use `:array?` without member rules? Or just let it be?

**Comment by solnic** [comment]
This is now fixed in master. I'll push 0.8.1 later today.
